FROM golang:1.23-alpine AS builder

WORKDIR /app

# Copy go mod files
COPY payment-service/go.mod payment-service/go.sum ./
RUN go mod download

# Copy source code
COPY payment-service/ ./

# Build the application
RUN go build -o bin/payment-service cmd/main.go

# Final stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata
WORKDIR /root/

# Copy the binary from builder stage
COPY --from=builder /app/bin/payment-service .

# Expose port
EXPOSE 8088

# Run the binary
CMD ["./payment-service"]