// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: proto/payment_verification.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Course Access Verification
type VerifyCourseAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	AuditInfo     *AccessAuditInfo       `protobuf:"bytes,3,opt,name=audit_info,json=auditInfo,proto3" json:"audit_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCourseAccessRequest) Reset() {
	*x = VerifyCourseAccessRequest{}
	mi := &file_proto_payment_verification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCourseAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCourseAccessRequest) ProtoMessage() {}

func (x *VerifyCourseAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCourseAccessRequest.ProtoReflect.Descriptor instead.
func (*VerifyCourseAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyCourseAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyCourseAccessRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *VerifyCourseAccessRequest) GetAuditInfo() *AccessAuditInfo {
	if x != nil {
		return x.AuditInfo
	}
	return nil
}

type VerifyCourseAccessResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId        string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	HasAccess       bool                   `protobuf:"varint,3,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	AccessLevel     string                 `protobuf:"bytes,4,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"` // full, preview, denied
	PaymentRequired bool                   `protobuf:"varint,5,opt,name=payment_required,json=paymentRequired,proto3" json:"payment_required,omitempty"`
	PaymentVerified bool                   `protobuf:"varint,6,opt,name=payment_verified,json=paymentVerified,proto3" json:"payment_verified,omitempty"`
	TransactionId   string                 `protobuf:"bytes,7,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AccessExpiresAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=access_expires_at,json=accessExpiresAt,proto3" json:"access_expires_at,omitempty"`
	CoursePrice     float64                `protobuf:"fixed64,9,opt,name=course_price,json=coursePrice,proto3" json:"course_price,omitempty"`
	Currency        string                 `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`
	CheckoutUrl     string                 `protobuf:"bytes,11,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	Message         string                 `protobuf:"bytes,12,opt,name=message,proto3" json:"message,omitempty"`
	CachedUntil     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=cached_until,json=cachedUntil,proto3" json:"cached_until,omitempty"`
	RiskScore       float64                `protobuf:"fixed64,14,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifyCourseAccessResponse) Reset() {
	*x = VerifyCourseAccessResponse{}
	mi := &file_proto_payment_verification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCourseAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCourseAccessResponse) ProtoMessage() {}

func (x *VerifyCourseAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCourseAccessResponse.ProtoReflect.Descriptor instead.
func (*VerifyCourseAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyCourseAccessResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyCourseAccessResponse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *VerifyCourseAccessResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

func (x *VerifyCourseAccessResponse) GetAccessLevel() string {
	if x != nil {
		return x.AccessLevel
	}
	return ""
}

func (x *VerifyCourseAccessResponse) GetPaymentRequired() bool {
	if x != nil {
		return x.PaymentRequired
	}
	return false
}

func (x *VerifyCourseAccessResponse) GetPaymentVerified() bool {
	if x != nil {
		return x.PaymentVerified
	}
	return false
}

func (x *VerifyCourseAccessResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *VerifyCourseAccessResponse) GetAccessExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessExpiresAt
	}
	return nil
}

func (x *VerifyCourseAccessResponse) GetCoursePrice() float64 {
	if x != nil {
		return x.CoursePrice
	}
	return 0
}

func (x *VerifyCourseAccessResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *VerifyCourseAccessResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *VerifyCourseAccessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerifyCourseAccessResponse) GetCachedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.CachedUntil
	}
	return nil
}

func (x *VerifyCourseAccessResponse) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

// Lecture Access Verification
type VerifyLectureAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LectureId     string                 `protobuf:"bytes,2,opt,name=lecture_id,json=lectureId,proto3" json:"lecture_id,omitempty"`
	AuditInfo     *AccessAuditInfo       `protobuf:"bytes,3,opt,name=audit_info,json=auditInfo,proto3" json:"audit_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyLectureAccessRequest) Reset() {
	*x = VerifyLectureAccessRequest{}
	mi := &file_proto_payment_verification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyLectureAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyLectureAccessRequest) ProtoMessage() {}

func (x *VerifyLectureAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyLectureAccessRequest.ProtoReflect.Descriptor instead.
func (*VerifyLectureAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyLectureAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyLectureAccessRequest) GetLectureId() string {
	if x != nil {
		return x.LectureId
	}
	return ""
}

func (x *VerifyLectureAccessRequest) GetAuditInfo() *AccessAuditInfo {
	if x != nil {
		return x.AuditInfo
	}
	return nil
}

type VerifyLectureAccessResponse struct {
	state                protoimpl.MessageState      `protogen:"open.v1"`
	UserId               string                      `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LectureId            string                      `protobuf:"bytes,2,opt,name=lecture_id,json=lectureId,proto3" json:"lecture_id,omitempty"`
	CourseId             string                      `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	HasAccess            bool                        `protobuf:"varint,4,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	AccessLevel          string                      `protobuf:"bytes,5,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
	IsPreview            bool                        `protobuf:"varint,6,opt,name=is_preview,json=isPreview,proto3" json:"is_preview,omitempty"`
	PreviewTimeRemaining int32                       `protobuf:"varint,7,opt,name=preview_time_remaining,json=previewTimeRemaining,proto3" json:"preview_time_remaining,omitempty"`
	CourseAccess         *VerifyCourseAccessResponse `protobuf:"bytes,8,opt,name=course_access,json=courseAccess,proto3" json:"course_access,omitempty"`
	Message              string                      `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *VerifyLectureAccessResponse) Reset() {
	*x = VerifyLectureAccessResponse{}
	mi := &file_proto_payment_verification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyLectureAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyLectureAccessResponse) ProtoMessage() {}

func (x *VerifyLectureAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyLectureAccessResponse.ProtoReflect.Descriptor instead.
func (*VerifyLectureAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyLectureAccessResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyLectureAccessResponse) GetLectureId() string {
	if x != nil {
		return x.LectureId
	}
	return ""
}

func (x *VerifyLectureAccessResponse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *VerifyLectureAccessResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

func (x *VerifyLectureAccessResponse) GetAccessLevel() string {
	if x != nil {
		return x.AccessLevel
	}
	return ""
}

func (x *VerifyLectureAccessResponse) GetIsPreview() bool {
	if x != nil {
		return x.IsPreview
	}
	return false
}

func (x *VerifyLectureAccessResponse) GetPreviewTimeRemaining() int32 {
	if x != nil {
		return x.PreviewTimeRemaining
	}
	return 0
}

func (x *VerifyLectureAccessResponse) GetCourseAccess() *VerifyCourseAccessResponse {
	if x != nil {
		return x.CourseAccess
	}
	return nil
}

func (x *VerifyLectureAccessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Transaction Operations
type GetUserTransactionsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	StatusFilter   string                 `protobuf:"bytes,4,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	CourseIdFilter string                 `protobuf:"bytes,5,opt,name=course_id_filter,json=courseIdFilter,proto3" json:"course_id_filter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserTransactionsRequest) Reset() {
	*x = GetUserTransactionsRequest{}
	mi := &file_proto_payment_verification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTransactionsRequest) ProtoMessage() {}

func (x *GetUserTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserTransactionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserTransactionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserTransactionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetUserTransactionsRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

func (x *GetUserTransactionsRequest) GetCourseIdFilter() string {
	if x != nil {
		return x.CourseIdFilter
	}
	return ""
}

type GetUserTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTransactionsResponse) Reset() {
	*x = GetUserTransactionsResponse{}
	mi := &file_proto_payment_verification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTransactionsResponse) ProtoMessage() {}

func (x *GetUserTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetUserTransactionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetUserTransactionsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_proto_payment_verification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *GetTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTransactionResponse struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	Transaction         *Transaction                `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	VerificationDetails *PaymentVerificationDetails `protobuf:"bytes,2,opt,name=verification_details,json=verificationDetails,proto3" json:"verification_details,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_proto_payment_verification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *GetTransactionResponse) GetVerificationDetails() *PaymentVerificationDetails {
	if x != nil {
		return x.VerificationDetails
	}
	return nil
}

type VerifyPaymentStatusRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TransactionId      string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ForceProviderCheck bool                   `protobuf:"varint,3,opt,name=force_provider_check,json=forceProviderCheck,proto3" json:"force_provider_check,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VerifyPaymentStatusRequest) Reset() {
	*x = VerifyPaymentStatusRequest{}
	mi := &file_proto_payment_verification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPaymentStatusRequest) ProtoMessage() {}

func (x *VerifyPaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*VerifyPaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyPaymentStatusRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *VerifyPaymentStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyPaymentStatusRequest) GetForceProviderCheck() bool {
	if x != nil {
		return x.ForceProviderCheck
	}
	return false
}

type VerifyPaymentStatusResponse struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	Transaction         *Transaction                `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	VerificationDetails *PaymentVerificationDetails `protobuf:"bytes,2,opt,name=verification_details,json=verificationDetails,proto3" json:"verification_details,omitempty"`
	AccessStatus        *VerifyCourseAccessResponse `protobuf:"bytes,3,opt,name=access_status,json=accessStatus,proto3" json:"access_status,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VerifyPaymentStatusResponse) Reset() {
	*x = VerifyPaymentStatusResponse{}
	mi := &file_proto_payment_verification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPaymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPaymentStatusResponse) ProtoMessage() {}

func (x *VerifyPaymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPaymentStatusResponse.ProtoReflect.Descriptor instead.
func (*VerifyPaymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyPaymentStatusResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *VerifyPaymentStatusResponse) GetVerificationDetails() *PaymentVerificationDetails {
	if x != nil {
		return x.VerificationDetails
	}
	return nil
}

func (x *VerifyPaymentStatusResponse) GetAccessStatus() *VerifyCourseAccessResponse {
	if x != nil {
		return x.AccessStatus
	}
	return nil
}

// Checkout Operations
type CreateCheckoutSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Options       *CheckoutOptions       `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	ClientIp      string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCheckoutSessionRequest) Reset() {
	*x = CreateCheckoutSessionRequest{}
	mi := &file_proto_payment_verification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckoutSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckoutSessionRequest) ProtoMessage() {}

func (x *CreateCheckoutSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckoutSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateCheckoutSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCheckoutSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCheckoutSessionRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CreateCheckoutSessionRequest) GetOptions() *CheckoutOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreateCheckoutSessionRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type CreateCheckoutSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckoutUrl   string                 `protobuf:"bytes,1,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	CheckoutId    string                 `protobuf:"bytes,2,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	TransactionId string                 `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCheckoutSessionResponse) Reset() {
	*x = CreateCheckoutSessionResponse{}
	mi := &file_proto_payment_verification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckoutSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckoutSessionResponse) ProtoMessage() {}

func (x *CreateCheckoutSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckoutSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateCheckoutSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{11}
}

func (x *CreateCheckoutSessionResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *CreateCheckoutSessionResponse) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

func (x *CreateCheckoutSessionResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CreateCheckoutSessionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// Preview Session Management
type UpdatePreviewSessionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LectureId       string                 `protobuf:"bytes,2,opt,name=lecture_id,json=lectureId,proto3" json:"lecture_id,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdatePreviewSessionRequest) Reset() {
	*x = UpdatePreviewSessionRequest{}
	mi := &file_proto_payment_verification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreviewSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreviewSessionRequest) ProtoMessage() {}

func (x *UpdatePreviewSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreviewSessionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreviewSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{12}
}

func (x *UpdatePreviewSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePreviewSessionRequest) GetLectureId() string {
	if x != nil {
		return x.LectureId
	}
	return ""
}

func (x *UpdatePreviewSessionRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type UpdatePreviewSessionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RemainingTime    int32                  `protobuf:"varint,2,opt,name=remaining_time,json=remainingTime,proto3" json:"remaining_time,omitempty"`
	PreviewExhausted bool                   `protobuf:"varint,3,opt,name=preview_exhausted,json=previewExhausted,proto3" json:"preview_exhausted,omitempty"`
	Message          string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdatePreviewSessionResponse) Reset() {
	*x = UpdatePreviewSessionResponse{}
	mi := &file_proto_payment_verification_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreviewSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreviewSessionResponse) ProtoMessage() {}

func (x *UpdatePreviewSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreviewSessionResponse.ProtoReflect.Descriptor instead.
func (*UpdatePreviewSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{13}
}

func (x *UpdatePreviewSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdatePreviewSessionResponse) GetRemainingTime() int32 {
	if x != nil {
		return x.RemainingTime
	}
	return 0
}

func (x *UpdatePreviewSessionResponse) GetPreviewExhausted() bool {
	if x != nil {
		return x.PreviewExhausted
	}
	return false
}

func (x *UpdatePreviewSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPreviewSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LectureId     string                 `protobuf:"bytes,2,opt,name=lecture_id,json=lectureId,proto3" json:"lecture_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreviewSessionRequest) Reset() {
	*x = GetPreviewSessionRequest{}
	mi := &file_proto_payment_verification_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreviewSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreviewSessionRequest) ProtoMessage() {}

func (x *GetPreviewSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreviewSessionRequest.ProtoReflect.Descriptor instead.
func (*GetPreviewSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{14}
}

func (x *GetPreviewSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPreviewSessionRequest) GetLectureId() string {
	if x != nil {
		return x.LectureId
	}
	return ""
}

type GetPreviewSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *PreviewSession        `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreviewSessionResponse) Reset() {
	*x = GetPreviewSessionResponse{}
	mi := &file_proto_payment_verification_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreviewSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreviewSessionResponse) ProtoMessage() {}

func (x *GetPreviewSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreviewSessionResponse.ProtoReflect.Descriptor instead.
func (*GetPreviewSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{15}
}

func (x *GetPreviewSessionResponse) GetSession() *PreviewSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *GetPreviewSessionResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// Cache Management
type ClearUserAccessCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearUserAccessCacheRequest) Reset() {
	*x = ClearUserAccessCacheRequest{}
	mi := &file_proto_payment_verification_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearUserAccessCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearUserAccessCacheRequest) ProtoMessage() {}

func (x *ClearUserAccessCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearUserAccessCacheRequest.ProtoReflect.Descriptor instead.
func (*ClearUserAccessCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{16}
}

func (x *ClearUserAccessCacheRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClearUserAccessCacheRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type ClearUserAccessCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearUserAccessCacheResponse) Reset() {
	*x = ClearUserAccessCacheResponse{}
	mi := &file_proto_payment_verification_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearUserAccessCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearUserAccessCacheResponse) ProtoMessage() {}

func (x *ClearUserAccessCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearUserAccessCacheResponse.ProtoReflect.Descriptor instead.
func (*ClearUserAccessCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{17}
}

func (x *ClearUserAccessCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClearUserAccessCacheResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Analytics
type GetAccessStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Days          int32                  `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	MetricType    string                 `protobuf:"bytes,3,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"` // access_attempts, revenue, conversions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessStatisticsRequest) Reset() {
	*x = GetAccessStatisticsRequest{}
	mi := &file_proto_payment_verification_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessStatisticsRequest) ProtoMessage() {}

func (x *GetAccessStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetAccessStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{18}
}

func (x *GetAccessStatisticsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *GetAccessStatisticsRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *GetAccessStatisticsRequest) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

type GetAccessStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statistics    *AccessStatistics      `protobuf:"bytes,1,opt,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessStatisticsResponse) Reset() {
	*x = GetAccessStatisticsResponse{}
	mi := &file_proto_payment_verification_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessStatisticsResponse) ProtoMessage() {}

func (x *GetAccessStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetAccessStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{19}
}

func (x *GetAccessStatisticsResponse) GetStatistics() *AccessStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

// Supporting Messages
type AccessAuditInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // course, lecture
	ClientIp      string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessAuditInfo) Reset() {
	*x = AccessAuditInfo{}
	mi := &file_proto_payment_verification_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessAuditInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessAuditInfo) ProtoMessage() {}

func (x *AccessAuditInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessAuditInfo.ProtoReflect.Descriptor instead.
func (*AccessAuditInfo) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{20}
}

func (x *AccessAuditInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccessAuditInfo) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *AccessAuditInfo) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *AccessAuditInfo) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *AccessAuditInfo) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AccessAuditInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Transaction struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId                 string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId               string                 `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Amount                 float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency               string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status                 string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	PaymentProvider        string                 `protobuf:"bytes,7,opt,name=payment_provider,json=paymentProvider,proto3" json:"payment_provider,omitempty"`
	LemonSqueezyOrderId    string                 `protobuf:"bytes,8,opt,name=lemon_squeezy_order_id,json=lemonSqueezyOrderId,proto3" json:"lemon_squeezy_order_id,omitempty"`
	LemonSqueezyCheckoutId string                 `protobuf:"bytes,9,opt,name=lemon_squeezy_checkout_id,json=lemonSqueezyCheckoutId,proto3" json:"lemon_squeezy_checkout_id,omitempty"`
	WebhookEventId         string                 `protobuf:"bytes,10,opt,name=webhook_event_id,json=webhookEventId,proto3" json:"webhook_event_id,omitempty"`
	PaymentVerifiedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=payment_verified_at,json=paymentVerifiedAt,proto3" json:"payment_verified_at,omitempty"`
	RefundedAt             *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=refunded_at,json=refundedAt,proto3" json:"refunded_at,omitempty"`
	ExpiresAt              *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CustomData             string                 `protobuf:"bytes,14,opt,name=custom_data,json=customData,proto3" json:"custom_data,omitempty"` // JSON string
	RiskScore              float64                `protobuf:"fixed64,15,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	CreatedAt              *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt              *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_payment_verification_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{21}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Transaction) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetPaymentProvider() string {
	if x != nil {
		return x.PaymentProvider
	}
	return ""
}

func (x *Transaction) GetLemonSqueezyOrderId() string {
	if x != nil {
		return x.LemonSqueezyOrderId
	}
	return ""
}

func (x *Transaction) GetLemonSqueezyCheckoutId() string {
	if x != nil {
		return x.LemonSqueezyCheckoutId
	}
	return ""
}

func (x *Transaction) GetWebhookEventId() string {
	if x != nil {
		return x.WebhookEventId
	}
	return ""
}

func (x *Transaction) GetPaymentVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaymentVerifiedAt
	}
	return nil
}

func (x *Transaction) GetRefundedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefundedAt
	}
	return nil
}

func (x *Transaction) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Transaction) GetCustomData() string {
	if x != nil {
		return x.CustomData
	}
	return ""
}

func (x *Transaction) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transaction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PaymentVerificationDetails struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProviderOrderId    string                 `protobuf:"bytes,1,opt,name=provider_order_id,json=providerOrderId,proto3" json:"provider_order_id,omitempty"`
	ProviderStatus     string                 `protobuf:"bytes,2,opt,name=provider_status,json=providerStatus,proto3" json:"provider_status,omitempty"`
	ProviderAmount     float64                `protobuf:"fixed64,3,opt,name=provider_amount,json=providerAmount,proto3" json:"provider_amount,omitempty"`
	ProviderCurrency   string                 `protobuf:"bytes,4,opt,name=provider_currency,json=providerCurrency,proto3" json:"provider_currency,omitempty"`
	VerifiedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	VerificationSource string                 `protobuf:"bytes,6,opt,name=verification_source,json=verificationSource,proto3" json:"verification_source,omitempty"` // webhook, api, manual
	ProviderDetails    string                 `protobuf:"bytes,7,opt,name=provider_details,json=providerDetails,proto3" json:"provider_details,omitempty"`          // JSON string
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PaymentVerificationDetails) Reset() {
	*x = PaymentVerificationDetails{}
	mi := &file_proto_payment_verification_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentVerificationDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentVerificationDetails) ProtoMessage() {}

func (x *PaymentVerificationDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentVerificationDetails.ProtoReflect.Descriptor instead.
func (*PaymentVerificationDetails) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{22}
}

func (x *PaymentVerificationDetails) GetProviderOrderId() string {
	if x != nil {
		return x.ProviderOrderId
	}
	return ""
}

func (x *PaymentVerificationDetails) GetProviderStatus() string {
	if x != nil {
		return x.ProviderStatus
	}
	return ""
}

func (x *PaymentVerificationDetails) GetProviderAmount() float64 {
	if x != nil {
		return x.ProviderAmount
	}
	return 0
}

func (x *PaymentVerificationDetails) GetProviderCurrency() string {
	if x != nil {
		return x.ProviderCurrency
	}
	return ""
}

func (x *PaymentVerificationDetails) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *PaymentVerificationDetails) GetVerificationSource() string {
	if x != nil {
		return x.VerificationSource
	}
	return ""
}

func (x *PaymentVerificationDetails) GetProviderDetails() string {
	if x != nil {
		return x.ProviderDetails
	}
	return ""
}

type CheckoutOptions struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SuccessUrl        string                 `protobuf:"bytes,1,opt,name=success_url,json=successUrl,proto3" json:"success_url,omitempty"`
	CancelUrl         string                 `protobuf:"bytes,2,opt,name=cancel_url,json=cancelUrl,proto3" json:"cancel_url,omitempty"`
	CustomerEmail     string                 `protobuf:"bytes,3,opt,name=customer_email,json=customerEmail,proto3" json:"customer_email,omitempty"`
	CustomerName      string                 `protobuf:"bytes,4,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	CustomData        string                 `protobuf:"bytes,5,opt,name=custom_data,json=customData,proto3" json:"custom_data,omitempty"` // JSON string
	EmbedCheckout     bool                   `protobuf:"varint,6,opt,name=embed_checkout,json=embedCheckout,proto3" json:"embed_checkout,omitempty"`
	PreferredCurrency string                 `protobuf:"bytes,7,opt,name=preferred_currency,json=preferredCurrency,proto3" json:"preferred_currency,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckoutOptions) Reset() {
	*x = CheckoutOptions{}
	mi := &file_proto_payment_verification_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutOptions) ProtoMessage() {}

func (x *CheckoutOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutOptions.ProtoReflect.Descriptor instead.
func (*CheckoutOptions) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{23}
}

func (x *CheckoutOptions) GetSuccessUrl() string {
	if x != nil {
		return x.SuccessUrl
	}
	return ""
}

func (x *CheckoutOptions) GetCancelUrl() string {
	if x != nil {
		return x.CancelUrl
	}
	return ""
}

func (x *CheckoutOptions) GetCustomerEmail() string {
	if x != nil {
		return x.CustomerEmail
	}
	return ""
}

func (x *CheckoutOptions) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *CheckoutOptions) GetCustomData() string {
	if x != nil {
		return x.CustomData
	}
	return ""
}

func (x *CheckoutOptions) GetEmbedCheckout() bool {
	if x != nil {
		return x.EmbedCheckout
	}
	return false
}

func (x *CheckoutOptions) GetPreferredCurrency() string {
	if x != nil {
		return x.PreferredCurrency
	}
	return ""
}

type PreviewSession struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId                 string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LectureId              string                 `protobuf:"bytes,3,opt,name=lecture_id,json=lectureId,proto3" json:"lecture_id,omitempty"`
	SessionStartedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=session_started_at,json=sessionStartedAt,proto3" json:"session_started_at,omitempty"`
	SessionDurationSeconds int32                  `protobuf:"varint,5,opt,name=session_duration_seconds,json=sessionDurationSeconds,proto3" json:"session_duration_seconds,omitempty"`
	PreviewLimitSeconds    int32                  `protobuf:"varint,6,opt,name=preview_limit_seconds,json=previewLimitSeconds,proto3" json:"preview_limit_seconds,omitempty"`
	PreviewExhausted       bool                   `protobuf:"varint,7,opt,name=preview_exhausted,json=previewExhausted,proto3" json:"preview_exhausted,omitempty"`
	IpAddress              string                 `protobuf:"bytes,8,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	LastAccessedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_accessed_at,json=lastAccessedAt,proto3" json:"last_accessed_at,omitempty"`
	CreatedAt              *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt              *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PreviewSession) Reset() {
	*x = PreviewSession{}
	mi := &file_proto_payment_verification_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewSession) ProtoMessage() {}

func (x *PreviewSession) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewSession.ProtoReflect.Descriptor instead.
func (*PreviewSession) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{24}
}

func (x *PreviewSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PreviewSession) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PreviewSession) GetLectureId() string {
	if x != nil {
		return x.LectureId
	}
	return ""
}

func (x *PreviewSession) GetSessionStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SessionStartedAt
	}
	return nil
}

func (x *PreviewSession) GetSessionDurationSeconds() int32 {
	if x != nil {
		return x.SessionDurationSeconds
	}
	return 0
}

func (x *PreviewSession) GetPreviewLimitSeconds() int32 {
	if x != nil {
		return x.PreviewLimitSeconds
	}
	return 0
}

func (x *PreviewSession) GetPreviewExhausted() bool {
	if x != nil {
		return x.PreviewExhausted
	}
	return false
}

func (x *PreviewSession) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *PreviewSession) GetLastAccessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAccessedAt
	}
	return nil
}

func (x *PreviewSession) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PreviewSession) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type AccessStatistics struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalAttempts         int64                  `protobuf:"varint,1,opt,name=total_attempts,json=totalAttempts,proto3" json:"total_attempts,omitempty"`
	SuccessfulAccess      int64                  `protobuf:"varint,2,opt,name=successful_access,json=successfulAccess,proto3" json:"successful_access,omitempty"`
	PreviewAccess         int64                  `protobuf:"varint,3,opt,name=preview_access,json=previewAccess,proto3" json:"preview_access,omitempty"`
	DeniedAccess          int64                  `protobuf:"varint,4,opt,name=denied_access,json=deniedAccess,proto3" json:"denied_access,omitempty"`
	UniqueUsers           int64                  `protobuf:"varint,5,opt,name=unique_users,json=uniqueUsers,proto3" json:"unique_users,omitempty"`
	SuccessRate           float64                `protobuf:"fixed64,6,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	ConversionRate        float64                `protobuf:"fixed64,7,opt,name=conversion_rate,json=conversionRate,proto3" json:"conversion_rate,omitempty"`
	TotalRevenue          float64                `protobuf:"fixed64,8,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	AverageRevenuePerUser float64                `protobuf:"fixed64,9,opt,name=average_revenue_per_user,json=averageRevenuePerUser,proto3" json:"average_revenue_per_user,omitempty"`
	DailyStats            []*DailyStatistic      `protobuf:"bytes,10,rep,name=daily_stats,json=dailyStats,proto3" json:"daily_stats,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AccessStatistics) Reset() {
	*x = AccessStatistics{}
	mi := &file_proto_payment_verification_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessStatistics) ProtoMessage() {}

func (x *AccessStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessStatistics.ProtoReflect.Descriptor instead.
func (*AccessStatistics) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{25}
}

func (x *AccessStatistics) GetTotalAttempts() int64 {
	if x != nil {
		return x.TotalAttempts
	}
	return 0
}

func (x *AccessStatistics) GetSuccessfulAccess() int64 {
	if x != nil {
		return x.SuccessfulAccess
	}
	return 0
}

func (x *AccessStatistics) GetPreviewAccess() int64 {
	if x != nil {
		return x.PreviewAccess
	}
	return 0
}

func (x *AccessStatistics) GetDeniedAccess() int64 {
	if x != nil {
		return x.DeniedAccess
	}
	return 0
}

func (x *AccessStatistics) GetUniqueUsers() int64 {
	if x != nil {
		return x.UniqueUsers
	}
	return 0
}

func (x *AccessStatistics) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *AccessStatistics) GetConversionRate() float64 {
	if x != nil {
		return x.ConversionRate
	}
	return 0
}

func (x *AccessStatistics) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *AccessStatistics) GetAverageRevenuePerUser() float64 {
	if x != nil {
		return x.AverageRevenuePerUser
	}
	return 0
}

func (x *AccessStatistics) GetDailyStats() []*DailyStatistic {
	if x != nil {
		return x.DailyStats
	}
	return nil
}

type DailyStatistic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD format
	Attempts      int64                  `protobuf:"varint,2,opt,name=attempts,proto3" json:"attempts,omitempty"`
	Successes     int64                  `protobuf:"varint,3,opt,name=successes,proto3" json:"successes,omitempty"`
	Conversions   int64                  `protobuf:"varint,4,opt,name=conversions,proto3" json:"conversions,omitempty"`
	Revenue       float64                `protobuf:"fixed64,5,opt,name=revenue,proto3" json:"revenue,omitempty"`
	UniqueUsers   int64                  `protobuf:"varint,6,opt,name=unique_users,json=uniqueUsers,proto3" json:"unique_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyStatistic) Reset() {
	*x = DailyStatistic{}
	mi := &file_proto_payment_verification_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyStatistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyStatistic) ProtoMessage() {}

func (x *DailyStatistic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyStatistic.ProtoReflect.Descriptor instead.
func (*DailyStatistic) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{26}
}

func (x *DailyStatistic) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyStatistic) GetAttempts() int64 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *DailyStatistic) GetSuccesses() int64 {
	if x != nil {
		return x.Successes
	}
	return 0
}

func (x *DailyStatistic) GetConversions() int64 {
	if x != nil {
		return x.Conversions
	}
	return 0
}

func (x *DailyStatistic) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *DailyStatistic) GetUniqueUsers() int64 {
	if x != nil {
		return x.UniqueUsers
	}
	return 0
}

// Error Handling
type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_proto_payment_verification_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{27}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ErrorResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode        string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ValidationErrors []*ValidationError     `protobuf:"bytes,3,rep,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"`
	TraceId          string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_proto_payment_verification_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_verification_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_verification_proto_rawDescGZIP(), []int{28}
}

func (x *ErrorResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ErrorResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ErrorResponse) GetValidationErrors() []*ValidationError {
	if x != nil {
		return x.ValidationErrors
	}
	return nil
}

func (x *ErrorResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_proto_payment_verification_proto protoreflect.FileDescriptor

const file_proto_payment_verification_proto_rawDesc = "" +
	"\n" +
	" proto/payment_verification.proto\x12\apayment\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x01\n" +
	"\x19VerifyCourseAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x127\n" +
	"\n" +
	"audit_info\x18\x03 \x01(\v2\x18.payment.AccessAuditInfoR\tauditInfo\"\xb3\x04\n" +
	"\x1aVerifyCourseAccessResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"has_access\x18\x03 \x01(\bR\thasAccess\x12!\n" +
	"\faccess_level\x18\x04 \x01(\tR\vaccessLevel\x12)\n" +
	"\x10payment_required\x18\x05 \x01(\bR\x0fpaymentRequired\x12)\n" +
	"\x10payment_verified\x18\x06 \x01(\bR\x0fpaymentVerified\x12%\n" +
	"\x0etransaction_id\x18\a \x01(\tR\rtransactionId\x12F\n" +
	"\x11access_expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0faccessExpiresAt\x12!\n" +
	"\fcourse_price\x18\t \x01(\x01R\vcoursePrice\x12\x1a\n" +
	"\bcurrency\x18\n" +
	" \x01(\tR\bcurrency\x12!\n" +
	"\fcheckout_url\x18\v \x01(\tR\vcheckoutUrl\x12\x18\n" +
	"\amessage\x18\f \x01(\tR\amessage\x12=\n" +
	"\fcached_until\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vcachedUntil\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x0e \x01(\x01R\triskScore\"\x8d\x01\n" +
	"\x1aVerifyLectureAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"lecture_id\x18\x02 \x01(\tR\tlectureId\x127\n" +
	"\n" +
	"audit_info\x18\x03 \x01(\v2\x18.payment.AccessAuditInfoR\tauditInfo\"\xed\x02\n" +
	"\x1bVerifyLectureAccessResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"lecture_id\x18\x02 \x01(\tR\tlectureId\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"has_access\x18\x04 \x01(\bR\thasAccess\x12!\n" +
	"\faccess_level\x18\x05 \x01(\tR\vaccessLevel\x12\x1d\n" +
	"\n" +
	"is_preview\x18\x06 \x01(\bR\tisPreview\x124\n" +
	"\x16preview_time_remaining\x18\a \x01(\x05R\x14previewTimeRemaining\x12H\n" +
	"\rcourse_access\x18\b \x01(\v2#.payment.VerifyCourseAccessResponseR\fcourseAccess\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\"\xb2\x01\n" +
	"\x1aGetUserTransactionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12#\n" +
	"\rstatus_filter\x18\x04 \x01(\tR\fstatusFilter\x12(\n" +
	"\x10course_id_filter\x18\x05 \x01(\tR\x0ecourseIdFilter\"\x93\x01\n" +
	"\x1bGetUserTransactionsResponse\x128\n" +
	"\ftransactions\x18\x01 \x03(\v2\x14.payment.TransactionR\ftransactions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"W\n" +
	"\x15GetTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xa8\x01\n" +
	"\x16GetTransactionResponse\x126\n" +
	"\vtransaction\x18\x01 \x01(\v2\x14.payment.TransactionR\vtransaction\x12V\n" +
	"\x14verification_details\x18\x02 \x01(\v2#.payment.PaymentVerificationDetailsR\x13verificationDetails\"\x8e\x01\n" +
	"\x1aVerifyPaymentStatusRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x120\n" +
	"\x14force_provider_check\x18\x03 \x01(\bR\x12forceProviderCheck\"\xf7\x01\n" +
	"\x1bVerifyPaymentStatusResponse\x126\n" +
	"\vtransaction\x18\x01 \x01(\v2\x14.payment.TransactionR\vtransaction\x12V\n" +
	"\x14verification_details\x18\x02 \x01(\v2#.payment.PaymentVerificationDetailsR\x13verificationDetails\x12H\n" +
	"\raccess_status\x18\x03 \x01(\v2#.payment.VerifyCourseAccessResponseR\faccessStatus\"\xa5\x01\n" +
	"\x1cCreateCheckoutSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x122\n" +
	"\aoptions\x18\x03 \x01(\v2\x18.payment.CheckoutOptionsR\aoptions\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\"\xc5\x01\n" +
	"\x1dCreateCheckoutSessionResponse\x12!\n" +
	"\fcheckout_url\x18\x01 \x01(\tR\vcheckoutUrl\x12\x1f\n" +
	"\vcheckout_id\x18\x02 \x01(\tR\n" +
	"checkoutId\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12%\n" +
	"\x0etransaction_id\x18\x04 \x01(\tR\rtransactionId\"\x80\x01\n" +
	"\x1bUpdatePreviewSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"lecture_id\x18\x02 \x01(\tR\tlectureId\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x05R\x0fdurationSeconds\"\xa6\x01\n" +
	"\x1cUpdatePreviewSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0eremaining_time\x18\x02 \x01(\x05R\rremainingTime\x12+\n" +
	"\x11preview_exhausted\x18\x03 \x01(\bR\x10previewExhausted\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"R\n" +
	"\x18GetPreviewSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"lecture_id\x18\x02 \x01(\tR\tlectureId\"f\n" +
	"\x19GetPreviewSessionResponse\x121\n" +
	"\asession\x18\x01 \x01(\v2\x17.payment.PreviewSessionR\asession\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"S\n" +
	"\x1bClearUserAccessCacheRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"R\n" +
	"\x1cClearUserAccessCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"n\n" +
	"\x1aGetAccessStatisticsRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x12\n" +
	"\x04days\x18\x02 \x01(\x05R\x04days\x12\x1f\n" +
	"\vmetric_type\x18\x03 \x01(\tR\n" +
	"metricType\"X\n" +
	"\x1bGetAccessStatisticsResponse\x129\n" +
	"\n" +
	"statistics\x18\x01 \x01(\v2\x19.payment.AccessStatisticsR\n" +
	"statistics\"\xcb\x01\n" +
	"\x0fAccessAuditInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\"\xde\x05\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12)\n" +
	"\x10payment_provider\x18\a \x01(\tR\x0fpaymentProvider\x123\n" +
	"\x16lemon_squeezy_order_id\x18\b \x01(\tR\x13lemonSqueezyOrderId\x129\n" +
	"\x19lemon_squeezy_checkout_id\x18\t \x01(\tR\x16lemonSqueezyCheckoutId\x12(\n" +
	"\x10webhook_event_id\x18\n" +
	" \x01(\tR\x0ewebhookEventId\x12J\n" +
	"\x13payment_verified_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x11paymentVerifiedAt\x12;\n" +
	"\vrefunded_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"refundedAt\x129\n" +
	"\n" +
	"expires_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1f\n" +
	"\vcustom_data\x18\x0e \x01(\tR\n" +
	"customData\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x0f \x01(\x01R\triskScore\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe0\x02\n" +
	"\x1aPaymentVerificationDetails\x12*\n" +
	"\x11provider_order_id\x18\x01 \x01(\tR\x0fproviderOrderId\x12'\n" +
	"\x0fprovider_status\x18\x02 \x01(\tR\x0eproviderStatus\x12'\n" +
	"\x0fprovider_amount\x18\x03 \x01(\x01R\x0eproviderAmount\x12+\n" +
	"\x11provider_currency\x18\x04 \x01(\tR\x10providerCurrency\x12;\n" +
	"\vverified_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\x12/\n" +
	"\x13verification_source\x18\x06 \x01(\tR\x12verificationSource\x12)\n" +
	"\x10provider_details\x18\a \x01(\tR\x0fproviderDetails\"\x94\x02\n" +
	"\x0fCheckoutOptions\x12\x1f\n" +
	"\vsuccess_url\x18\x01 \x01(\tR\n" +
	"successUrl\x12\x1d\n" +
	"\n" +
	"cancel_url\x18\x02 \x01(\tR\tcancelUrl\x12%\n" +
	"\x0ecustomer_email\x18\x03 \x01(\tR\rcustomerEmail\x12#\n" +
	"\rcustomer_name\x18\x04 \x01(\tR\fcustomerName\x12\x1f\n" +
	"\vcustom_data\x18\x05 \x01(\tR\n" +
	"customData\x12%\n" +
	"\x0eembed_checkout\x18\x06 \x01(\bR\rembedCheckout\x12-\n" +
	"\x12preferred_currency\x18\a \x01(\tR\x11preferredCurrency\"\x98\x04\n" +
	"\x0ePreviewSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"lecture_id\x18\x03 \x01(\tR\tlectureId\x12H\n" +
	"\x12session_started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x10sessionStartedAt\x128\n" +
	"\x18session_duration_seconds\x18\x05 \x01(\x05R\x16sessionDurationSeconds\x122\n" +
	"\x15preview_limit_seconds\x18\x06 \x01(\x05R\x13previewLimitSeconds\x12+\n" +
	"\x11preview_exhausted\x18\a \x01(\bR\x10previewExhausted\x12\x1d\n" +
	"\n" +
	"ip_address\x18\b \x01(\tR\tipAddress\x12D\n" +
	"\x10last_accessed_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0elastAccessedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb9\x03\n" +
	"\x10AccessStatistics\x12%\n" +
	"\x0etotal_attempts\x18\x01 \x01(\x03R\rtotalAttempts\x12+\n" +
	"\x11successful_access\x18\x02 \x01(\x03R\x10successfulAccess\x12%\n" +
	"\x0epreview_access\x18\x03 \x01(\x03R\rpreviewAccess\x12#\n" +
	"\rdenied_access\x18\x04 \x01(\x03R\fdeniedAccess\x12!\n" +
	"\funique_users\x18\x05 \x01(\x03R\vuniqueUsers\x12!\n" +
	"\fsuccess_rate\x18\x06 \x01(\x01R\vsuccessRate\x12'\n" +
	"\x0fconversion_rate\x18\a \x01(\x01R\x0econversionRate\x12#\n" +
	"\rtotal_revenue\x18\b \x01(\x01R\ftotalRevenue\x127\n" +
	"\x18average_revenue_per_user\x18\t \x01(\x01R\x15averageRevenuePerUser\x128\n" +
	"\vdaily_stats\x18\n" +
	" \x03(\v2\x17.payment.DailyStatisticR\n" +
	"dailyStats\"\xbd\x01\n" +
	"\x0eDailyStatistic\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1a\n" +
	"\battempts\x18\x02 \x01(\x03R\battempts\x12\x1c\n" +
	"\tsuccesses\x18\x03 \x01(\x03R\tsuccesses\x12 \n" +
	"\vconversions\x18\x04 \x01(\x03R\vconversions\x12\x18\n" +
	"\arevenue\x18\x05 \x01(\x01R\arevenue\x12!\n" +
	"\funique_users\x18\x06 \x01(\x03R\vuniqueUsers\"U\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\xb5\x01\n" +
	"\rErrorResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12E\n" +
	"\x11validation_errors\x18\x03 \x03(\v2\x18.payment.ValidationErrorR\x10validationErrors\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId2\xe4\a\n" +
	"\x1aPaymentVerificationService\x12]\n" +
	"\x12VerifyCourseAccess\x12\".payment.VerifyCourseAccessRequest\x1a#.payment.VerifyCourseAccessResponse\x12`\n" +
	"\x13VerifyLectureAccess\x12#.payment.VerifyLectureAccessRequest\x1a$.payment.VerifyLectureAccessResponse\x12`\n" +
	"\x13GetUserTransactions\x12#.payment.GetUserTransactionsRequest\x1a$.payment.GetUserTransactionsResponse\x12Q\n" +
	"\x0eGetTransaction\x12\x1e.payment.GetTransactionRequest\x1a\x1f.payment.GetTransactionResponse\x12`\n" +
	"\x13VerifyPaymentStatus\x12#.payment.VerifyPaymentStatusRequest\x1a$.payment.VerifyPaymentStatusResponse\x12f\n" +
	"\x15CreateCheckoutSession\x12%.payment.CreateCheckoutSessionRequest\x1a&.payment.CreateCheckoutSessionResponse\x12c\n" +
	"\x14UpdatePreviewSession\x12$.payment.UpdatePreviewSessionRequest\x1a%.payment.UpdatePreviewSessionResponse\x12Z\n" +
	"\x11GetPreviewSession\x12!.payment.GetPreviewSessionRequest\x1a\".payment.GetPreviewSessionResponse\x12c\n" +
	"\x14ClearUserAccessCache\x12$.payment.ClearUserAccessCacheRequest\x1a%.payment.ClearUserAccessCacheResponse\x12`\n" +
	"\x13GetAccessStatistics\x12#.payment.GetAccessStatisticsRequest\x1a$.payment.GetAccessStatisticsResponseB9Z7github.com/study-platform/payment-service/proto;paymentb\x06proto3"

var (
	file_proto_payment_verification_proto_rawDescOnce sync.Once
	file_proto_payment_verification_proto_rawDescData []byte
)

func file_proto_payment_verification_proto_rawDescGZIP() []byte {
	file_proto_payment_verification_proto_rawDescOnce.Do(func() {
		file_proto_payment_verification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_verification_proto_rawDesc), len(file_proto_payment_verification_proto_rawDesc)))
	})
	return file_proto_payment_verification_proto_rawDescData
}

var file_proto_payment_verification_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_payment_verification_proto_goTypes = []any{
	(*VerifyCourseAccessRequest)(nil),     // 0: payment.VerifyCourseAccessRequest
	(*VerifyCourseAccessResponse)(nil),    // 1: payment.VerifyCourseAccessResponse
	(*VerifyLectureAccessRequest)(nil),    // 2: payment.VerifyLectureAccessRequest
	(*VerifyLectureAccessResponse)(nil),   // 3: payment.VerifyLectureAccessResponse
	(*GetUserTransactionsRequest)(nil),    // 4: payment.GetUserTransactionsRequest
	(*GetUserTransactionsResponse)(nil),   // 5: payment.GetUserTransactionsResponse
	(*GetTransactionRequest)(nil),         // 6: payment.GetTransactionRequest
	(*GetTransactionResponse)(nil),        // 7: payment.GetTransactionResponse
	(*VerifyPaymentStatusRequest)(nil),    // 8: payment.VerifyPaymentStatusRequest
	(*VerifyPaymentStatusResponse)(nil),   // 9: payment.VerifyPaymentStatusResponse
	(*CreateCheckoutSessionRequest)(nil),  // 10: payment.CreateCheckoutSessionRequest
	(*CreateCheckoutSessionResponse)(nil), // 11: payment.CreateCheckoutSessionResponse
	(*UpdatePreviewSessionRequest)(nil),   // 12: payment.UpdatePreviewSessionRequest
	(*UpdatePreviewSessionResponse)(nil),  // 13: payment.UpdatePreviewSessionResponse
	(*GetPreviewSessionRequest)(nil),      // 14: payment.GetPreviewSessionRequest
	(*GetPreviewSessionResponse)(nil),     // 15: payment.GetPreviewSessionResponse
	(*ClearUserAccessCacheRequest)(nil),   // 16: payment.ClearUserAccessCacheRequest
	(*ClearUserAccessCacheResponse)(nil),  // 17: payment.ClearUserAccessCacheResponse
	(*GetAccessStatisticsRequest)(nil),    // 18: payment.GetAccessStatisticsRequest
	(*GetAccessStatisticsResponse)(nil),   // 19: payment.GetAccessStatisticsResponse
	(*AccessAuditInfo)(nil),               // 20: payment.AccessAuditInfo
	(*Transaction)(nil),                   // 21: payment.Transaction
	(*PaymentVerificationDetails)(nil),    // 22: payment.PaymentVerificationDetails
	(*CheckoutOptions)(nil),               // 23: payment.CheckoutOptions
	(*PreviewSession)(nil),                // 24: payment.PreviewSession
	(*AccessStatistics)(nil),              // 25: payment.AccessStatistics
	(*DailyStatistic)(nil),                // 26: payment.DailyStatistic
	(*ValidationError)(nil),               // 27: payment.ValidationError
	(*ErrorResponse)(nil),                 // 28: payment.ErrorResponse
	(*timestamppb.Timestamp)(nil),         // 29: google.protobuf.Timestamp
}
var file_proto_payment_verification_proto_depIdxs = []int32{
	20, // 0: payment.VerifyCourseAccessRequest.audit_info:type_name -> payment.AccessAuditInfo
	29, // 1: payment.VerifyCourseAccessResponse.access_expires_at:type_name -> google.protobuf.Timestamp
	29, // 2: payment.VerifyCourseAccessResponse.cached_until:type_name -> google.protobuf.Timestamp
	20, // 3: payment.VerifyLectureAccessRequest.audit_info:type_name -> payment.AccessAuditInfo
	1,  // 4: payment.VerifyLectureAccessResponse.course_access:type_name -> payment.VerifyCourseAccessResponse
	21, // 5: payment.GetUserTransactionsResponse.transactions:type_name -> payment.Transaction
	21, // 6: payment.GetTransactionResponse.transaction:type_name -> payment.Transaction
	22, // 7: payment.GetTransactionResponse.verification_details:type_name -> payment.PaymentVerificationDetails
	21, // 8: payment.VerifyPaymentStatusResponse.transaction:type_name -> payment.Transaction
	22, // 9: payment.VerifyPaymentStatusResponse.verification_details:type_name -> payment.PaymentVerificationDetails
	1,  // 10: payment.VerifyPaymentStatusResponse.access_status:type_name -> payment.VerifyCourseAccessResponse
	23, // 11: payment.CreateCheckoutSessionRequest.options:type_name -> payment.CheckoutOptions
	29, // 12: payment.CreateCheckoutSessionResponse.expires_at:type_name -> google.protobuf.Timestamp
	24, // 13: payment.GetPreviewSessionResponse.session:type_name -> payment.PreviewSession
	25, // 14: payment.GetAccessStatisticsResponse.statistics:type_name -> payment.AccessStatistics
	29, // 15: payment.Transaction.payment_verified_at:type_name -> google.protobuf.Timestamp
	29, // 16: payment.Transaction.refunded_at:type_name -> google.protobuf.Timestamp
	29, // 17: payment.Transaction.expires_at:type_name -> google.protobuf.Timestamp
	29, // 18: payment.Transaction.created_at:type_name -> google.protobuf.Timestamp
	29, // 19: payment.Transaction.updated_at:type_name -> google.protobuf.Timestamp
	29, // 20: payment.PaymentVerificationDetails.verified_at:type_name -> google.protobuf.Timestamp
	29, // 21: payment.PreviewSession.session_started_at:type_name -> google.protobuf.Timestamp
	29, // 22: payment.PreviewSession.last_accessed_at:type_name -> google.protobuf.Timestamp
	29, // 23: payment.PreviewSession.created_at:type_name -> google.protobuf.Timestamp
	29, // 24: payment.PreviewSession.updated_at:type_name -> google.protobuf.Timestamp
	26, // 25: payment.AccessStatistics.daily_stats:type_name -> payment.DailyStatistic
	27, // 26: payment.ErrorResponse.validation_errors:type_name -> payment.ValidationError
	0,  // 27: payment.PaymentVerificationService.VerifyCourseAccess:input_type -> payment.VerifyCourseAccessRequest
	2,  // 28: payment.PaymentVerificationService.VerifyLectureAccess:input_type -> payment.VerifyLectureAccessRequest
	4,  // 29: payment.PaymentVerificationService.GetUserTransactions:input_type -> payment.GetUserTransactionsRequest
	6,  // 30: payment.PaymentVerificationService.GetTransaction:input_type -> payment.GetTransactionRequest
	8,  // 31: payment.PaymentVerificationService.VerifyPaymentStatus:input_type -> payment.VerifyPaymentStatusRequest
	10, // 32: payment.PaymentVerificationService.CreateCheckoutSession:input_type -> payment.CreateCheckoutSessionRequest
	12, // 33: payment.PaymentVerificationService.UpdatePreviewSession:input_type -> payment.UpdatePreviewSessionRequest
	14, // 34: payment.PaymentVerificationService.GetPreviewSession:input_type -> payment.GetPreviewSessionRequest
	16, // 35: payment.PaymentVerificationService.ClearUserAccessCache:input_type -> payment.ClearUserAccessCacheRequest
	18, // 36: payment.PaymentVerificationService.GetAccessStatistics:input_type -> payment.GetAccessStatisticsRequest
	1,  // 37: payment.PaymentVerificationService.VerifyCourseAccess:output_type -> payment.VerifyCourseAccessResponse
	3,  // 38: payment.PaymentVerificationService.VerifyLectureAccess:output_type -> payment.VerifyLectureAccessResponse
	5,  // 39: payment.PaymentVerificationService.GetUserTransactions:output_type -> payment.GetUserTransactionsResponse
	7,  // 40: payment.PaymentVerificationService.GetTransaction:output_type -> payment.GetTransactionResponse
	9,  // 41: payment.PaymentVerificationService.VerifyPaymentStatus:output_type -> payment.VerifyPaymentStatusResponse
	11, // 42: payment.PaymentVerificationService.CreateCheckoutSession:output_type -> payment.CreateCheckoutSessionResponse
	13, // 43: payment.PaymentVerificationService.UpdatePreviewSession:output_type -> payment.UpdatePreviewSessionResponse
	15, // 44: payment.PaymentVerificationService.GetPreviewSession:output_type -> payment.GetPreviewSessionResponse
	17, // 45: payment.PaymentVerificationService.ClearUserAccessCache:output_type -> payment.ClearUserAccessCacheResponse
	19, // 46: payment.PaymentVerificationService.GetAccessStatistics:output_type -> payment.GetAccessStatisticsResponse
	37, // [37:47] is the sub-list for method output_type
	27, // [27:37] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_proto_payment_verification_proto_init() }
func file_proto_payment_verification_proto_init() {
	if File_proto_payment_verification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_verification_proto_rawDesc), len(file_proto_payment_verification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_verification_proto_goTypes,
		DependencyIndexes: file_proto_payment_verification_proto_depIdxs,
		MessageInfos:      file_proto_payment_verification_proto_msgTypes,
	}.Build()
	File_proto_payment_verification_proto = out.File
	file_proto_payment_verification_proto_goTypes = nil
	file_proto_payment_verification_proto_depIdxs = nil
}
