// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: proto/progress.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Core messages
type UserProgress struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId           string                 `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	LectureId          string                 `protobuf:"bytes,4,opt,name=lecture_id,json=lectureId,proto3" json:"lecture_id,omitempty"`
	ProgressPercentage float64                `protobuf:"fixed64,5,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	WatchTimeSeconds   int32                  `protobuf:"varint,6,opt,name=watch_time_seconds,json=watchTimeSeconds,proto3" json:"watch_time_seconds,omitempty"`
	IsCompleted        bool                   `protobuf:"varint,7,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	LastAccessed       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_accessed,json=lastAccessed,proto3" json:"last_accessed,omitempty"`
	CompletedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserProgress) Reset() {
	*x = UserProgress{}
	mi := &file_proto_progress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProgress) ProtoMessage() {}

func (x *UserProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProgress.ProtoReflect.Descriptor instead.
func (*UserProgress) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{0}
}

func (x *UserProgress) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProgress) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProgress) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *UserProgress) GetLectureId() string {
	if x != nil {
		return x.LectureId
	}
	return ""
}

func (x *UserProgress) GetProgressPercentage() float64 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *UserProgress) GetWatchTimeSeconds() int32 {
	if x != nil {
		return x.WatchTimeSeconds
	}
	return 0
}

func (x *UserProgress) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *UserProgress) GetLastAccessed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAccessed
	}
	return nil
}

func (x *UserProgress) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *UserProgress) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserProgress) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Enrollment struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId                string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId              string                 `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Status                string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // enrolled, completed, cancelled, suspended
	ProgressPercentage    float64                `protobuf:"fixed64,5,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	CompletedLectures     int32                  `protobuf:"varint,6,opt,name=completed_lectures,json=completedLectures,proto3" json:"completed_lectures,omitempty"`
	TotalLectures         int32                  `protobuf:"varint,7,opt,name=total_lectures,json=totalLectures,proto3" json:"total_lectures,omitempty"`
	TotalWatchTimeSeconds int32                  `protobuf:"varint,8,opt,name=total_watch_time_seconds,json=totalWatchTimeSeconds,proto3" json:"total_watch_time_seconds,omitempty"`
	EnrolledAt            *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=enrolled_at,json=enrolledAt,proto3" json:"enrolled_at,omitempty"`
	CompletedAt           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	LastAccessed          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_accessed,json=lastAccessed,proto3" json:"last_accessed,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Enrollment) Reset() {
	*x = Enrollment{}
	mi := &file_proto_progress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enrollment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enrollment) ProtoMessage() {}

func (x *Enrollment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enrollment.ProtoReflect.Descriptor instead.
func (*Enrollment) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{1}
}

func (x *Enrollment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Enrollment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Enrollment) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Enrollment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Enrollment) GetProgressPercentage() float64 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *Enrollment) GetCompletedLectures() int32 {
	if x != nil {
		return x.CompletedLectures
	}
	return 0
}

func (x *Enrollment) GetTotalLectures() int32 {
	if x != nil {
		return x.TotalLectures
	}
	return 0
}

func (x *Enrollment) GetTotalWatchTimeSeconds() int32 {
	if x != nil {
		return x.TotalWatchTimeSeconds
	}
	return 0
}

func (x *Enrollment) GetEnrolledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnrolledAt
	}
	return nil
}

func (x *Enrollment) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Enrollment) GetLastAccessed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAccessed
	}
	return nil
}

func (x *Enrollment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Enrollment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type LectureProgress struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LectureId          string                 `protobuf:"bytes,1,opt,name=lecture_id,json=lectureId,proto3" json:"lecture_id,omitempty"`
	Title              string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	OrderNumber        int32                  `protobuf:"varint,3,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	ProgressPercentage float64                `protobuf:"fixed64,4,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	WatchTimeSeconds   int32                  `protobuf:"varint,5,opt,name=watch_time_seconds,json=watchTimeSeconds,proto3" json:"watch_time_seconds,omitempty"`
	IsCompleted        bool                   `protobuf:"varint,6,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	LastAccessed       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_accessed,json=lastAccessed,proto3" json:"last_accessed,omitempty"`
	CompletedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LectureProgress) Reset() {
	*x = LectureProgress{}
	mi := &file_proto_progress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LectureProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LectureProgress) ProtoMessage() {}

func (x *LectureProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LectureProgress.ProtoReflect.Descriptor instead.
func (*LectureProgress) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{2}
}

func (x *LectureProgress) GetLectureId() string {
	if x != nil {
		return x.LectureId
	}
	return ""
}

func (x *LectureProgress) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LectureProgress) GetOrderNumber() int32 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *LectureProgress) GetProgressPercentage() float64 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *LectureProgress) GetWatchTimeSeconds() int32 {
	if x != nil {
		return x.WatchTimeSeconds
	}
	return 0
}

func (x *LectureProgress) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *LectureProgress) GetLastAccessed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAccessed
	}
	return nil
}

func (x *LectureProgress) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type CourseCompletion struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CourseId              string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	CourseTitle           string                 `protobuf:"bytes,2,opt,name=course_title,json=courseTitle,proto3" json:"course_title,omitempty"`
	UserId                string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompletionPercentage  float64                `protobuf:"fixed64,4,opt,name=completion_percentage,json=completionPercentage,proto3" json:"completion_percentage,omitempty"`
	CompletedLectures     int32                  `protobuf:"varint,5,opt,name=completed_lectures,json=completedLectures,proto3" json:"completed_lectures,omitempty"`
	TotalLectures         int32                  `protobuf:"varint,6,opt,name=total_lectures,json=totalLectures,proto3" json:"total_lectures,omitempty"`
	TotalWatchTimeSeconds int32                  `protobuf:"varint,7,opt,name=total_watch_time_seconds,json=totalWatchTimeSeconds,proto3" json:"total_watch_time_seconds,omitempty"`
	LectureProgress       []*LectureProgress     `protobuf:"bytes,8,rep,name=lecture_progress,json=lectureProgress,proto3" json:"lecture_progress,omitempty"`
	StartedAt             *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	LastAccessed          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_accessed,json=lastAccessed,proto3" json:"last_accessed,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CourseCompletion) Reset() {
	*x = CourseCompletion{}
	mi := &file_proto_progress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseCompletion) ProtoMessage() {}

func (x *CourseCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseCompletion.ProtoReflect.Descriptor instead.
func (*CourseCompletion) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{3}
}

func (x *CourseCompletion) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CourseCompletion) GetCourseTitle() string {
	if x != nil {
		return x.CourseTitle
	}
	return ""
}

func (x *CourseCompletion) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CourseCompletion) GetCompletionPercentage() float64 {
	if x != nil {
		return x.CompletionPercentage
	}
	return 0
}

func (x *CourseCompletion) GetCompletedLectures() int32 {
	if x != nil {
		return x.CompletedLectures
	}
	return 0
}

func (x *CourseCompletion) GetTotalLectures() int32 {
	if x != nil {
		return x.TotalLectures
	}
	return 0
}

func (x *CourseCompletion) GetTotalWatchTimeSeconds() int32 {
	if x != nil {
		return x.TotalWatchTimeSeconds
	}
	return 0
}

func (x *CourseCompletion) GetLectureProgress() []*LectureProgress {
	if x != nil {
		return x.LectureProgress
	}
	return nil
}

func (x *CourseCompletion) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CourseCompletion) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *CourseCompletion) GetLastAccessed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAccessed
	}
	return nil
}

type UserAnalytics struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	UserId                    string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalCoursesEnrolled      int32                  `protobuf:"varint,2,opt,name=total_courses_enrolled,json=totalCoursesEnrolled,proto3" json:"total_courses_enrolled,omitempty"`
	TotalCoursesCompleted     int32                  `protobuf:"varint,3,opt,name=total_courses_completed,json=totalCoursesCompleted,proto3" json:"total_courses_completed,omitempty"`
	TotalLecturesCompleted    int32                  `protobuf:"varint,4,opt,name=total_lectures_completed,json=totalLecturesCompleted,proto3" json:"total_lectures_completed,omitempty"`
	TotalWatchTimeSeconds     int32                  `protobuf:"varint,5,opt,name=total_watch_time_seconds,json=totalWatchTimeSeconds,proto3" json:"total_watch_time_seconds,omitempty"`
	AverageProgressPercentage float64                `protobuf:"fixed64,6,opt,name=average_progress_percentage,json=averageProgressPercentage,proto3" json:"average_progress_percentage,omitempty"`
	CoursesInProgress         int32                  `protobuf:"varint,7,opt,name=courses_in_progress,json=coursesInProgress,proto3" json:"courses_in_progress,omitempty"`
	MostActiveDay             string                 `protobuf:"bytes,8,opt,name=most_active_day,json=mostActiveDay,proto3" json:"most_active_day,omitempty"`
	StreakDays                int32                  `protobuf:"varint,9,opt,name=streak_days,json=streakDays,proto3" json:"streak_days,omitempty"`
	LastActivity              *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *UserAnalytics) Reset() {
	*x = UserAnalytics{}
	mi := &file_proto_progress_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAnalytics) ProtoMessage() {}

func (x *UserAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAnalytics.ProtoReflect.Descriptor instead.
func (*UserAnalytics) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{4}
}

func (x *UserAnalytics) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserAnalytics) GetTotalCoursesEnrolled() int32 {
	if x != nil {
		return x.TotalCoursesEnrolled
	}
	return 0
}

func (x *UserAnalytics) GetTotalCoursesCompleted() int32 {
	if x != nil {
		return x.TotalCoursesCompleted
	}
	return 0
}

func (x *UserAnalytics) GetTotalLecturesCompleted() int32 {
	if x != nil {
		return x.TotalLecturesCompleted
	}
	return 0
}

func (x *UserAnalytics) GetTotalWatchTimeSeconds() int32 {
	if x != nil {
		return x.TotalWatchTimeSeconds
	}
	return 0
}

func (x *UserAnalytics) GetAverageProgressPercentage() float64 {
	if x != nil {
		return x.AverageProgressPercentage
	}
	return 0
}

func (x *UserAnalytics) GetCoursesInProgress() int32 {
	if x != nil {
		return x.CoursesInProgress
	}
	return 0
}

func (x *UserAnalytics) GetMostActiveDay() string {
	if x != nil {
		return x.MostActiveDay
	}
	return ""
}

func (x *UserAnalytics) GetStreakDays() int32 {
	if x != nil {
		return x.StreakDays
	}
	return 0
}

func (x *UserAnalytics) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivity
	}
	return nil
}

type CourseAnalytics struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	CourseId                   string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	TotalEnrollments           int32                  `protobuf:"varint,2,opt,name=total_enrollments,json=totalEnrollments,proto3" json:"total_enrollments,omitempty"`
	TotalCompletions           int32                  `protobuf:"varint,3,opt,name=total_completions,json=totalCompletions,proto3" json:"total_completions,omitempty"`
	CompletionRate             float64                `protobuf:"fixed64,4,opt,name=completion_rate,json=completionRate,proto3" json:"completion_rate,omitempty"`
	AverageProgressPercentage  float64                `protobuf:"fixed64,5,opt,name=average_progress_percentage,json=averageProgressPercentage,proto3" json:"average_progress_percentage,omitempty"`
	ActiveStudents             int32                  `protobuf:"varint,6,opt,name=active_students,json=activeStudents,proto3" json:"active_students,omitempty"`
	TotalWatchTimeSeconds      int32                  `protobuf:"varint,7,opt,name=total_watch_time_seconds,json=totalWatchTimeSeconds,proto3" json:"total_watch_time_seconds,omitempty"`
	AverageWatchTimePerStudent float64                `protobuf:"fixed64,8,opt,name=average_watch_time_per_student,json=averageWatchTimePerStudent,proto3" json:"average_watch_time_per_student,omitempty"`
	MostPopularLecture         string                 `protobuf:"bytes,9,opt,name=most_popular_lecture,json=mostPopularLecture,proto3" json:"most_popular_lecture,omitempty"`
	DropoutRate                float64                `protobuf:"fixed64,10,opt,name=dropout_rate,json=dropoutRate,proto3" json:"dropout_rate,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CourseAnalytics) Reset() {
	*x = CourseAnalytics{}
	mi := &file_proto_progress_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseAnalytics) ProtoMessage() {}

func (x *CourseAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseAnalytics.ProtoReflect.Descriptor instead.
func (*CourseAnalytics) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{5}
}

func (x *CourseAnalytics) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CourseAnalytics) GetTotalEnrollments() int32 {
	if x != nil {
		return x.TotalEnrollments
	}
	return 0
}

func (x *CourseAnalytics) GetTotalCompletions() int32 {
	if x != nil {
		return x.TotalCompletions
	}
	return 0
}

func (x *CourseAnalytics) GetCompletionRate() float64 {
	if x != nil {
		return x.CompletionRate
	}
	return 0
}

func (x *CourseAnalytics) GetAverageProgressPercentage() float64 {
	if x != nil {
		return x.AverageProgressPercentage
	}
	return 0
}

func (x *CourseAnalytics) GetActiveStudents() int32 {
	if x != nil {
		return x.ActiveStudents
	}
	return 0
}

func (x *CourseAnalytics) GetTotalWatchTimeSeconds() int32 {
	if x != nil {
		return x.TotalWatchTimeSeconds
	}
	return 0
}

func (x *CourseAnalytics) GetAverageWatchTimePerStudent() float64 {
	if x != nil {
		return x.AverageWatchTimePerStudent
	}
	return 0
}

func (x *CourseAnalytics) GetMostPopularLecture() string {
	if x != nil {
		return x.MostPopularLecture
	}
	return ""
}

func (x *CourseAnalytics) GetDropoutRate() float64 {
	if x != nil {
		return x.DropoutRate
	}
	return 0
}

type InstructorAnalytics struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	InstructorId          string                 `protobuf:"bytes,1,opt,name=instructor_id,json=instructorId,proto3" json:"instructor_id,omitempty"`
	TotalCourses          int32                  `protobuf:"varint,2,opt,name=total_courses,json=totalCourses,proto3" json:"total_courses,omitempty"`
	TotalStudents         int32                  `protobuf:"varint,3,opt,name=total_students,json=totalStudents,proto3" json:"total_students,omitempty"`
	TotalCompletions      int32                  `protobuf:"varint,4,opt,name=total_completions,json=totalCompletions,proto3" json:"total_completions,omitempty"`
	AverageCompletionRate float64                `protobuf:"fixed64,5,opt,name=average_completion_rate,json=averageCompletionRate,proto3" json:"average_completion_rate,omitempty"`
	TotalWatchTimeSeconds int32                  `protobuf:"varint,6,opt,name=total_watch_time_seconds,json=totalWatchTimeSeconds,proto3" json:"total_watch_time_seconds,omitempty"`
	AverageCourseRating   float64                `protobuf:"fixed64,7,opt,name=average_course_rating,json=averageCourseRating,proto3" json:"average_course_rating,omitempty"`
	ActiveCourses         int32                  `protobuf:"varint,8,opt,name=active_courses,json=activeCourses,proto3" json:"active_courses,omitempty"`
	BestPerformingCourse  string                 `protobuf:"bytes,9,opt,name=best_performing_course,json=bestPerformingCourse,proto3" json:"best_performing_course,omitempty"`
	TotalRevenueCents     int32                  `protobuf:"varint,10,opt,name=total_revenue_cents,json=totalRevenueCents,proto3" json:"total_revenue_cents,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InstructorAnalytics) Reset() {
	*x = InstructorAnalytics{}
	mi := &file_proto_progress_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstructorAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructorAnalytics) ProtoMessage() {}

func (x *InstructorAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructorAnalytics.ProtoReflect.Descriptor instead.
func (*InstructorAnalytics) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{6}
}

func (x *InstructorAnalytics) GetInstructorId() string {
	if x != nil {
		return x.InstructorId
	}
	return ""
}

func (x *InstructorAnalytics) GetTotalCourses() int32 {
	if x != nil {
		return x.TotalCourses
	}
	return 0
}

func (x *InstructorAnalytics) GetTotalStudents() int32 {
	if x != nil {
		return x.TotalStudents
	}
	return 0
}

func (x *InstructorAnalytics) GetTotalCompletions() int32 {
	if x != nil {
		return x.TotalCompletions
	}
	return 0
}

func (x *InstructorAnalytics) GetAverageCompletionRate() float64 {
	if x != nil {
		return x.AverageCompletionRate
	}
	return 0
}

func (x *InstructorAnalytics) GetTotalWatchTimeSeconds() int32 {
	if x != nil {
		return x.TotalWatchTimeSeconds
	}
	return 0
}

func (x *InstructorAnalytics) GetAverageCourseRating() float64 {
	if x != nil {
		return x.AverageCourseRating
	}
	return 0
}

func (x *InstructorAnalytics) GetActiveCourses() int32 {
	if x != nil {
		return x.ActiveCourses
	}
	return 0
}

func (x *InstructorAnalytics) GetBestPerformingCourse() string {
	if x != nil {
		return x.BestPerformingCourse
	}
	return ""
}

func (x *InstructorAnalytics) GetTotalRevenueCents() int32 {
	if x != nil {
		return x.TotalRevenueCents
	}
	return 0
}

// Progress requests/responses
type UpdateProgressRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId           string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	LectureId          string                 `protobuf:"bytes,3,opt,name=lecture_id,json=lectureId,proto3" json:"lecture_id,omitempty"`
	ProgressPercentage float64                `protobuf:"fixed64,4,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	WatchTimeSeconds   int32                  `protobuf:"varint,5,opt,name=watch_time_seconds,json=watchTimeSeconds,proto3" json:"watch_time_seconds,omitempty"`
	IsCompleted        bool                   `protobuf:"varint,6,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateProgressRequest) Reset() {
	*x = UpdateProgressRequest{}
	mi := &file_proto_progress_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressRequest) ProtoMessage() {}

func (x *UpdateProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressRequest.ProtoReflect.Descriptor instead.
func (*UpdateProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProgressRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *UpdateProgressRequest) GetLectureId() string {
	if x != nil {
		return x.LectureId
	}
	return ""
}

func (x *UpdateProgressRequest) GetProgressPercentage() float64 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *UpdateProgressRequest) GetWatchTimeSeconds() int32 {
	if x != nil {
		return x.WatchTimeSeconds
	}
	return 0
}

func (x *UpdateProgressRequest) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

type UpdateProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      *UserProgress          `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProgressResponse) Reset() {
	*x = UpdateProgressResponse{}
	mi := &file_proto_progress_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressResponse) ProtoMessage() {}

func (x *UpdateProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressResponse.ProtoReflect.Descriptor instead.
func (*UpdateProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProgressResponse) GetProgress() *UserProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *UpdateProgressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	LectureId     string                 `protobuf:"bytes,3,opt,name=lecture_id,json=lectureId,proto3" json:"lecture_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressRequest) Reset() {
	*x = GetProgressRequest{}
	mi := &file_proto_progress_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressRequest) ProtoMessage() {}

func (x *GetProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressRequest.ProtoReflect.Descriptor instead.
func (*GetProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{9}
}

func (x *GetProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProgressRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *GetProgressRequest) GetLectureId() string {
	if x != nil {
		return x.LectureId
	}
	return ""
}

type GetProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      *UserProgress          `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressResponse) Reset() {
	*x = GetProgressResponse{}
	mi := &file_proto_progress_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressResponse) ProtoMessage() {}

func (x *GetProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressResponse.ProtoReflect.Descriptor instead.
func (*GetProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{10}
}

func (x *GetProgressResponse) GetProgress() *UserProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type GetUserProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProgressRequest) Reset() {
	*x = GetUserProgressRequest{}
	mi := &file_proto_progress_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProgressRequest) ProtoMessage() {}

func (x *GetUserProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProgressRequest.ProtoReflect.Descriptor instead.
func (*GetUserProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserProgressRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GetUserProgressResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Progress                  []*UserProgress        `protobuf:"bytes,1,rep,name=progress,proto3" json:"progress,omitempty"`
	OverallProgressPercentage float64                `protobuf:"fixed64,2,opt,name=overall_progress_percentage,json=overallProgressPercentage,proto3" json:"overall_progress_percentage,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GetUserProgressResponse) Reset() {
	*x = GetUserProgressResponse{}
	mi := &file_proto_progress_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProgressResponse) ProtoMessage() {}

func (x *GetUserProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProgressResponse.ProtoReflect.Descriptor instead.
func (*GetUserProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserProgressResponse) GetProgress() []*UserProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *GetUserProgressResponse) GetOverallProgressPercentage() float64 {
	if x != nil {
		return x.OverallProgressPercentage
	}
	return 0
}

type GetCourseProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseProgressRequest) Reset() {
	*x = GetCourseProgressRequest{}
	mi := &file_proto_progress_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseProgressRequest) ProtoMessage() {}

func (x *GetCourseProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseProgressRequest.ProtoReflect.Descriptor instead.
func (*GetCourseProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{13}
}

func (x *GetCourseProgressRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *GetCourseProgressRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCourseProgressRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetCourseProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      []*UserProgress        `protobuf:"bytes,1,rep,name=progress,proto3" json:"progress,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseProgressResponse) Reset() {
	*x = GetCourseProgressResponse{}
	mi := &file_proto_progress_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseProgressResponse) ProtoMessage() {}

func (x *GetCourseProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseProgressResponse.ProtoReflect.Descriptor instead.
func (*GetCourseProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{14}
}

func (x *GetCourseProgressResponse) GetProgress() []*UserProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *GetCourseProgressResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetCourseProgressResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCourseProgressResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Enrollment requests/responses
type CreateEnrollmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnrollmentRequest) Reset() {
	*x = CreateEnrollmentRequest{}
	mi := &file_proto_progress_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnrollmentRequest) ProtoMessage() {}

func (x *CreateEnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnrollmentRequest.ProtoReflect.Descriptor instead.
func (*CreateEnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{15}
}

func (x *CreateEnrollmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateEnrollmentRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type CreateEnrollmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrollment    *Enrollment            `protobuf:"bytes,1,opt,name=enrollment,proto3" json:"enrollment,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnrollmentResponse) Reset() {
	*x = CreateEnrollmentResponse{}
	mi := &file_proto_progress_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnrollmentResponse) ProtoMessage() {}

func (x *CreateEnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnrollmentResponse.ProtoReflect.Descriptor instead.
func (*CreateEnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{16}
}

func (x *CreateEnrollmentResponse) GetEnrollment() *Enrollment {
	if x != nil {
		return x.Enrollment
	}
	return nil
}

func (x *CreateEnrollmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetEnrollmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnrollmentRequest) Reset() {
	*x = GetEnrollmentRequest{}
	mi := &file_proto_progress_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnrollmentRequest) ProtoMessage() {}

func (x *GetEnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnrollmentRequest.ProtoReflect.Descriptor instead.
func (*GetEnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{17}
}

func (x *GetEnrollmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetEnrollmentRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GetEnrollmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrollment    *Enrollment            `protobuf:"bytes,1,opt,name=enrollment,proto3" json:"enrollment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnrollmentResponse) Reset() {
	*x = GetEnrollmentResponse{}
	mi := &file_proto_progress_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnrollmentResponse) ProtoMessage() {}

func (x *GetEnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnrollmentResponse.ProtoReflect.Descriptor instead.
func (*GetEnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{18}
}

func (x *GetEnrollmentResponse) GetEnrollment() *Enrollment {
	if x != nil {
		return x.Enrollment
	}
	return nil
}

type ListEnrollmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnrollmentsRequest) Reset() {
	*x = ListEnrollmentsRequest{}
	mi := &file_proto_progress_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnrollmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnrollmentsRequest) ProtoMessage() {}

func (x *ListEnrollmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnrollmentsRequest.ProtoReflect.Descriptor instead.
func (*ListEnrollmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{19}
}

func (x *ListEnrollmentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListEnrollmentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListEnrollmentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEnrollmentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListEnrollmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrollments   []*Enrollment          `protobuf:"bytes,1,rep,name=enrollments,proto3" json:"enrollments,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnrollmentsResponse) Reset() {
	*x = ListEnrollmentsResponse{}
	mi := &file_proto_progress_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnrollmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnrollmentsResponse) ProtoMessage() {}

func (x *ListEnrollmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnrollmentsResponse.ProtoReflect.Descriptor instead.
func (*ListEnrollmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{20}
}

func (x *ListEnrollmentsResponse) GetEnrollments() []*Enrollment {
	if x != nil {
		return x.Enrollments
	}
	return nil
}

func (x *ListEnrollmentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListEnrollmentsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEnrollmentsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateEnrollmentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEnrollmentStatusRequest) Reset() {
	*x = UpdateEnrollmentStatusRequest{}
	mi := &file_proto_progress_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnrollmentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnrollmentStatusRequest) ProtoMessage() {}

func (x *UpdateEnrollmentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnrollmentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateEnrollmentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateEnrollmentStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateEnrollmentStatusRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *UpdateEnrollmentStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateEnrollmentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrollment    *Enrollment            `protobuf:"bytes,1,opt,name=enrollment,proto3" json:"enrollment,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEnrollmentStatusResponse) Reset() {
	*x = UpdateEnrollmentStatusResponse{}
	mi := &file_proto_progress_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnrollmentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnrollmentStatusResponse) ProtoMessage() {}

func (x *UpdateEnrollmentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnrollmentStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateEnrollmentStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateEnrollmentStatusResponse) GetEnrollment() *Enrollment {
	if x != nil {
		return x.Enrollment
	}
	return nil
}

func (x *UpdateEnrollmentStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Course completion requests/responses
type MarkLectureCompleteRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId         string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	LectureId        string                 `protobuf:"bytes,3,opt,name=lecture_id,json=lectureId,proto3" json:"lecture_id,omitempty"`
	WatchTimeSeconds int32                  `protobuf:"varint,4,opt,name=watch_time_seconds,json=watchTimeSeconds,proto3" json:"watch_time_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MarkLectureCompleteRequest) Reset() {
	*x = MarkLectureCompleteRequest{}
	mi := &file_proto_progress_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkLectureCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkLectureCompleteRequest) ProtoMessage() {}

func (x *MarkLectureCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkLectureCompleteRequest.ProtoReflect.Descriptor instead.
func (*MarkLectureCompleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{23}
}

func (x *MarkLectureCompleteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MarkLectureCompleteRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *MarkLectureCompleteRequest) GetLectureId() string {
	if x != nil {
		return x.LectureId
	}
	return ""
}

func (x *MarkLectureCompleteRequest) GetWatchTimeSeconds() int32 {
	if x != nil {
		return x.WatchTimeSeconds
	}
	return 0
}

type MarkLectureCompleteResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Progress        *UserProgress          `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	CourseCompleted bool                   `protobuf:"varint,2,opt,name=course_completed,json=courseCompleted,proto3" json:"course_completed,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarkLectureCompleteResponse) Reset() {
	*x = MarkLectureCompleteResponse{}
	mi := &file_proto_progress_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkLectureCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkLectureCompleteResponse) ProtoMessage() {}

func (x *MarkLectureCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkLectureCompleteResponse.ProtoReflect.Descriptor instead.
func (*MarkLectureCompleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{24}
}

func (x *MarkLectureCompleteResponse) GetProgress() *UserProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *MarkLectureCompleteResponse) GetCourseCompleted() bool {
	if x != nil {
		return x.CourseCompleted
	}
	return false
}

func (x *MarkLectureCompleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLectureProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLectureProgressRequest) Reset() {
	*x = GetLectureProgressRequest{}
	mi := &file_proto_progress_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLectureProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLectureProgressRequest) ProtoMessage() {}

func (x *GetLectureProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLectureProgressRequest.ProtoReflect.Descriptor instead.
func (*GetLectureProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{25}
}

func (x *GetLectureProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetLectureProgressRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GetLectureProgressResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LectureProgress []*LectureProgress     `protobuf:"bytes,1,rep,name=lecture_progress,json=lectureProgress,proto3" json:"lecture_progress,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLectureProgressResponse) Reset() {
	*x = GetLectureProgressResponse{}
	mi := &file_proto_progress_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLectureProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLectureProgressResponse) ProtoMessage() {}

func (x *GetLectureProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLectureProgressResponse.ProtoReflect.Descriptor instead.
func (*GetLectureProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{26}
}

func (x *GetLectureProgressResponse) GetLectureProgress() []*LectureProgress {
	if x != nil {
		return x.LectureProgress
	}
	return nil
}

type GetCourseCompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseCompletionRequest) Reset() {
	*x = GetCourseCompletionRequest{}
	mi := &file_proto_progress_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseCompletionRequest) ProtoMessage() {}

func (x *GetCourseCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseCompletionRequest.ProtoReflect.Descriptor instead.
func (*GetCourseCompletionRequest) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{27}
}

func (x *GetCourseCompletionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetCourseCompletionRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GetCourseCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Completion    *CourseCompletion      `protobuf:"bytes,1,opt,name=completion,proto3" json:"completion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseCompletionResponse) Reset() {
	*x = GetCourseCompletionResponse{}
	mi := &file_proto_progress_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseCompletionResponse) ProtoMessage() {}

func (x *GetCourseCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseCompletionResponse.ProtoReflect.Descriptor instead.
func (*GetCourseCompletionResponse) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{28}
}

func (x *GetCourseCompletionResponse) GetCompletion() *CourseCompletion {
	if x != nil {
		return x.Completion
	}
	return nil
}

// Analytics requests/responses
type GetUserAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAnalyticsRequest) Reset() {
	*x = GetUserAnalyticsRequest{}
	mi := &file_proto_progress_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAnalyticsRequest) ProtoMessage() {}

func (x *GetUserAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetUserAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{29}
}

func (x *GetUserAnalyticsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserAnalyticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analytics     *UserAnalytics         `protobuf:"bytes,1,opt,name=analytics,proto3" json:"analytics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAnalyticsResponse) Reset() {
	*x = GetUserAnalyticsResponse{}
	mi := &file_proto_progress_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAnalyticsResponse) ProtoMessage() {}

func (x *GetUserAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GetUserAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{30}
}

func (x *GetUserAnalyticsResponse) GetAnalytics() *UserAnalytics {
	if x != nil {
		return x.Analytics
	}
	return nil
}

type GetCourseAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseAnalyticsRequest) Reset() {
	*x = GetCourseAnalyticsRequest{}
	mi := &file_proto_progress_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseAnalyticsRequest) ProtoMessage() {}

func (x *GetCourseAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetCourseAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{31}
}

func (x *GetCourseAnalyticsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GetCourseAnalyticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analytics     *CourseAnalytics       `protobuf:"bytes,1,opt,name=analytics,proto3" json:"analytics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseAnalyticsResponse) Reset() {
	*x = GetCourseAnalyticsResponse{}
	mi := &file_proto_progress_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseAnalyticsResponse) ProtoMessage() {}

func (x *GetCourseAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GetCourseAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{32}
}

func (x *GetCourseAnalyticsResponse) GetAnalytics() *CourseAnalytics {
	if x != nil {
		return x.Analytics
	}
	return nil
}

type GetInstructorAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstructorId  string                 `protobuf:"bytes,1,opt,name=instructor_id,json=instructorId,proto3" json:"instructor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstructorAnalyticsRequest) Reset() {
	*x = GetInstructorAnalyticsRequest{}
	mi := &file_proto_progress_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstructorAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstructorAnalyticsRequest) ProtoMessage() {}

func (x *GetInstructorAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstructorAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetInstructorAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{33}
}

func (x *GetInstructorAnalyticsRequest) GetInstructorId() string {
	if x != nil {
		return x.InstructorId
	}
	return ""
}

type GetInstructorAnalyticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analytics     *InstructorAnalytics   `protobuf:"bytes,1,opt,name=analytics,proto3" json:"analytics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstructorAnalyticsResponse) Reset() {
	*x = GetInstructorAnalyticsResponse{}
	mi := &file_proto_progress_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstructorAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstructorAnalyticsResponse) ProtoMessage() {}

func (x *GetInstructorAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_progress_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstructorAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GetInstructorAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_progress_proto_rawDescGZIP(), []int{34}
}

func (x *GetInstructorAnalyticsResponse) GetAnalytics() *InstructorAnalytics {
	if x != nil {
		return x.Analytics
	}
	return nil
}

var File_proto_progress_proto protoreflect.FileDescriptor

const file_proto_progress_proto_rawDesc = "" +
	"\n" +
	"\x14proto/progress.proto\x12\bprogress\x1a\x1fgoogle/protobuf/timestamp.proto\"\xeb\x03\n" +
	"\fUserProgress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"lecture_id\x18\x04 \x01(\tR\tlectureId\x12/\n" +
	"\x13progress_percentage\x18\x05 \x01(\x01R\x12progressPercentage\x12,\n" +
	"\x12watch_time_seconds\x18\x06 \x01(\x05R\x10watchTimeSeconds\x12!\n" +
	"\fis_completed\x18\a \x01(\bR\visCompleted\x12?\n" +
	"\rlast_accessed\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\flastAccessed\x12=\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xdd\x04\n" +
	"\n" +
	"Enrollment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12/\n" +
	"\x13progress_percentage\x18\x05 \x01(\x01R\x12progressPercentage\x12-\n" +
	"\x12completed_lectures\x18\x06 \x01(\x05R\x11completedLectures\x12%\n" +
	"\x0etotal_lectures\x18\a \x01(\x05R\rtotalLectures\x127\n" +
	"\x18total_watch_time_seconds\x18\b \x01(\x05R\x15totalWatchTimeSeconds\x12;\n" +
	"\venrolled_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enrolledAt\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12?\n" +
	"\rlast_accessed\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\flastAccessed\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xeb\x02\n" +
	"\x0fLectureProgress\x12\x1d\n" +
	"\n" +
	"lecture_id\x18\x01 \x01(\tR\tlectureId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\forder_number\x18\x03 \x01(\x05R\vorderNumber\x12/\n" +
	"\x13progress_percentage\x18\x04 \x01(\x01R\x12progressPercentage\x12,\n" +
	"\x12watch_time_seconds\x18\x05 \x01(\x05R\x10watchTimeSeconds\x12!\n" +
	"\fis_completed\x18\x06 \x01(\bR\visCompleted\x12?\n" +
	"\rlast_accessed\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\flastAccessed\x12=\n" +
	"\fcompleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xb0\x04\n" +
	"\x10CourseCompletion\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12!\n" +
	"\fcourse_title\x18\x02 \x01(\tR\vcourseTitle\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x123\n" +
	"\x15completion_percentage\x18\x04 \x01(\x01R\x14completionPercentage\x12-\n" +
	"\x12completed_lectures\x18\x05 \x01(\x05R\x11completedLectures\x12%\n" +
	"\x0etotal_lectures\x18\x06 \x01(\x05R\rtotalLectures\x127\n" +
	"\x18total_watch_time_seconds\x18\a \x01(\x05R\x15totalWatchTimeSeconds\x12D\n" +
	"\x10lecture_progress\x18\b \x03(\v2\x19.progress.LectureProgressR\x0flectureProgress\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12?\n" +
	"\rlast_accessed\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\flastAccessed\"\x83\x04\n" +
	"\rUserAnalytics\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x124\n" +
	"\x16total_courses_enrolled\x18\x02 \x01(\x05R\x14totalCoursesEnrolled\x126\n" +
	"\x17total_courses_completed\x18\x03 \x01(\x05R\x15totalCoursesCompleted\x128\n" +
	"\x18total_lectures_completed\x18\x04 \x01(\x05R\x16totalLecturesCompleted\x127\n" +
	"\x18total_watch_time_seconds\x18\x05 \x01(\x05R\x15totalWatchTimeSeconds\x12>\n" +
	"\x1baverage_progress_percentage\x18\x06 \x01(\x01R\x19averageProgressPercentage\x12.\n" +
	"\x13courses_in_progress\x18\a \x01(\x05R\x11coursesInProgress\x12&\n" +
	"\x0fmost_active_day\x18\b \x01(\tR\rmostActiveDay\x12\x1f\n" +
	"\vstreak_days\x18\t \x01(\x05R\n" +
	"streakDays\x12?\n" +
	"\rlast_activity\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\flastActivity\"\xec\x03\n" +
	"\x0fCourseAnalytics\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12+\n" +
	"\x11total_enrollments\x18\x02 \x01(\x05R\x10totalEnrollments\x12+\n" +
	"\x11total_completions\x18\x03 \x01(\x05R\x10totalCompletions\x12'\n" +
	"\x0fcompletion_rate\x18\x04 \x01(\x01R\x0ecompletionRate\x12>\n" +
	"\x1baverage_progress_percentage\x18\x05 \x01(\x01R\x19averageProgressPercentage\x12'\n" +
	"\x0factive_students\x18\x06 \x01(\x05R\x0eactiveStudents\x127\n" +
	"\x18total_watch_time_seconds\x18\a \x01(\x05R\x15totalWatchTimeSeconds\x12B\n" +
	"\x1eaverage_watch_time_per_student\x18\b \x01(\x01R\x1aaverageWatchTimePerStudent\x120\n" +
	"\x14most_popular_lecture\x18\t \x01(\tR\x12mostPopularLecture\x12!\n" +
	"\fdropout_rate\x18\n" +
	" \x01(\x01R\vdropoutRate\"\xe5\x03\n" +
	"\x13InstructorAnalytics\x12#\n" +
	"\rinstructor_id\x18\x01 \x01(\tR\finstructorId\x12#\n" +
	"\rtotal_courses\x18\x02 \x01(\x05R\ftotalCourses\x12%\n" +
	"\x0etotal_students\x18\x03 \x01(\x05R\rtotalStudents\x12+\n" +
	"\x11total_completions\x18\x04 \x01(\x05R\x10totalCompletions\x126\n" +
	"\x17average_completion_rate\x18\x05 \x01(\x01R\x15averageCompletionRate\x127\n" +
	"\x18total_watch_time_seconds\x18\x06 \x01(\x05R\x15totalWatchTimeSeconds\x122\n" +
	"\x15average_course_rating\x18\a \x01(\x01R\x13averageCourseRating\x12%\n" +
	"\x0eactive_courses\x18\b \x01(\x05R\ractiveCourses\x124\n" +
	"\x16best_performing_course\x18\t \x01(\tR\x14bestPerformingCourse\x12.\n" +
	"\x13total_revenue_cents\x18\n" +
	" \x01(\x05R\x11totalRevenueCents\"\xee\x01\n" +
	"\x15UpdateProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"lecture_id\x18\x03 \x01(\tR\tlectureId\x12/\n" +
	"\x13progress_percentage\x18\x04 \x01(\x01R\x12progressPercentage\x12,\n" +
	"\x12watch_time_seconds\x18\x05 \x01(\x05R\x10watchTimeSeconds\x12!\n" +
	"\fis_completed\x18\x06 \x01(\bR\visCompleted\"f\n" +
	"\x16UpdateProgressResponse\x122\n" +
	"\bprogress\x18\x01 \x01(\v2\x16.progress.UserProgressR\bprogress\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"i\n" +
	"\x12GetProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"lecture_id\x18\x03 \x01(\tR\tlectureId\"I\n" +
	"\x13GetProgressResponse\x122\n" +
	"\bprogress\x18\x01 \x01(\v2\x16.progress.UserProgressR\bprogress\"N\n" +
	"\x16GetUserProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"\x8d\x01\n" +
	"\x17GetUserProgressResponse\x122\n" +
	"\bprogress\x18\x01 \x03(\v2\x16.progress.UserProgressR\bprogress\x12>\n" +
	"\x1boverall_progress_percentage\x18\x02 \x01(\x01R\x19overallProgressPercentage\"h\n" +
	"\x18GetCourseProgressRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xa1\x01\n" +
	"\x19GetCourseProgressResponse\x122\n" +
	"\bprogress\x18\x01 \x03(\v2\x16.progress.UserProgressR\bprogress\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"O\n" +
	"\x17CreateEnrollmentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"j\n" +
	"\x18CreateEnrollmentResponse\x124\n" +
	"\n" +
	"enrollment\x18\x01 \x01(\v2\x14.progress.EnrollmentR\n" +
	"enrollment\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\x14GetEnrollmentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"M\n" +
	"\x15GetEnrollmentResponse\x124\n" +
	"\n" +
	"enrollment\x18\x01 \x01(\v2\x14.progress.EnrollmentR\n" +
	"enrollment\"z\n" +
	"\x16ListEnrollmentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xa3\x01\n" +
	"\x17ListEnrollmentsResponse\x126\n" +
	"\venrollments\x18\x01 \x03(\v2\x14.progress.EnrollmentR\venrollments\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"m\n" +
	"\x1dUpdateEnrollmentStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"p\n" +
	"\x1eUpdateEnrollmentStatusResponse\x124\n" +
	"\n" +
	"enrollment\x18\x01 \x01(\v2\x14.progress.EnrollmentR\n" +
	"enrollment\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9f\x01\n" +
	"\x1aMarkLectureCompleteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"lecture_id\x18\x03 \x01(\tR\tlectureId\x12,\n" +
	"\x12watch_time_seconds\x18\x04 \x01(\x05R\x10watchTimeSeconds\"\x96\x01\n" +
	"\x1bMarkLectureCompleteResponse\x122\n" +
	"\bprogress\x18\x01 \x01(\v2\x16.progress.UserProgressR\bprogress\x12)\n" +
	"\x10course_completed\x18\x02 \x01(\bR\x0fcourseCompleted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"Q\n" +
	"\x19GetLectureProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"b\n" +
	"\x1aGetLectureProgressResponse\x12D\n" +
	"\x10lecture_progress\x18\x01 \x03(\v2\x19.progress.LectureProgressR\x0flectureProgress\"R\n" +
	"\x1aGetCourseCompletionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"Y\n" +
	"\x1bGetCourseCompletionResponse\x12:\n" +
	"\n" +
	"completion\x18\x01 \x01(\v2\x1a.progress.CourseCompletionR\n" +
	"completion\"2\n" +
	"\x17GetUserAnalyticsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Q\n" +
	"\x18GetUserAnalyticsResponse\x125\n" +
	"\tanalytics\x18\x01 \x01(\v2\x17.progress.UserAnalyticsR\tanalytics\"8\n" +
	"\x19GetCourseAnalyticsRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"U\n" +
	"\x1aGetCourseAnalyticsResponse\x127\n" +
	"\tanalytics\x18\x01 \x01(\v2\x19.progress.CourseAnalyticsR\tanalytics\"D\n" +
	"\x1dGetInstructorAnalyticsRequest\x12#\n" +
	"\rinstructor_id\x18\x01 \x01(\tR\finstructorId\"]\n" +
	"\x1eGetInstructorAnalyticsResponse\x12;\n" +
	"\tanalytics\x18\x01 \x01(\v2\x1d.progress.InstructorAnalyticsR\tanalytics2\xac\n" +
	"\n" +
	"\x0fProgressService\x12S\n" +
	"\x0eUpdateProgress\x12\x1f.progress.UpdateProgressRequest\x1a .progress.UpdateProgressResponse\x12J\n" +
	"\vGetProgress\x12\x1c.progress.GetProgressRequest\x1a\x1d.progress.GetProgressResponse\x12V\n" +
	"\x0fGetUserProgress\x12 .progress.GetUserProgressRequest\x1a!.progress.GetUserProgressResponse\x12\\\n" +
	"\x11GetCourseProgress\x12\".progress.GetCourseProgressRequest\x1a#.progress.GetCourseProgressResponse\x12Y\n" +
	"\x10CreateEnrollment\x12!.progress.CreateEnrollmentRequest\x1a\".progress.CreateEnrollmentResponse\x12P\n" +
	"\rGetEnrollment\x12\x1e.progress.GetEnrollmentRequest\x1a\x1f.progress.GetEnrollmentResponse\x12V\n" +
	"\x0fListEnrollments\x12 .progress.ListEnrollmentsRequest\x1a!.progress.ListEnrollmentsResponse\x12k\n" +
	"\x16UpdateEnrollmentStatus\x12'.progress.UpdateEnrollmentStatusRequest\x1a(.progress.UpdateEnrollmentStatusResponse\x12b\n" +
	"\x13MarkLectureComplete\x12$.progress.MarkLectureCompleteRequest\x1a%.progress.MarkLectureCompleteResponse\x12_\n" +
	"\x12GetLectureProgress\x12#.progress.GetLectureProgressRequest\x1a$.progress.GetLectureProgressResponse\x12b\n" +
	"\x13GetCourseCompletion\x12$.progress.GetCourseCompletionRequest\x1a%.progress.GetCourseCompletionResponse\x12Y\n" +
	"\x10GetUserAnalytics\x12!.progress.GetUserAnalyticsRequest\x1a\".progress.GetUserAnalyticsResponse\x12_\n" +
	"\x12GetCourseAnalytics\x12#.progress.GetCourseAnalyticsRequest\x1a$.progress.GetCourseAnalyticsResponse\x12k\n" +
	"\x16GetInstructorAnalytics\x12'.progress.GetInstructorAnalyticsRequest\x1a(.progress.GetInstructorAnalyticsResponseB2Z0github.com/study-platform/progress-service/protob\x06proto3"

var (
	file_proto_progress_proto_rawDescOnce sync.Once
	file_proto_progress_proto_rawDescData []byte
)

func file_proto_progress_proto_rawDescGZIP() []byte {
	file_proto_progress_proto_rawDescOnce.Do(func() {
		file_proto_progress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_progress_proto_rawDesc), len(file_proto_progress_proto_rawDesc)))
	})
	return file_proto_progress_proto_rawDescData
}

var file_proto_progress_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_proto_progress_proto_goTypes = []any{
	(*UserProgress)(nil),                   // 0: progress.UserProgress
	(*Enrollment)(nil),                     // 1: progress.Enrollment
	(*LectureProgress)(nil),                // 2: progress.LectureProgress
	(*CourseCompletion)(nil),               // 3: progress.CourseCompletion
	(*UserAnalytics)(nil),                  // 4: progress.UserAnalytics
	(*CourseAnalytics)(nil),                // 5: progress.CourseAnalytics
	(*InstructorAnalytics)(nil),            // 6: progress.InstructorAnalytics
	(*UpdateProgressRequest)(nil),          // 7: progress.UpdateProgressRequest
	(*UpdateProgressResponse)(nil),         // 8: progress.UpdateProgressResponse
	(*GetProgressRequest)(nil),             // 9: progress.GetProgressRequest
	(*GetProgressResponse)(nil),            // 10: progress.GetProgressResponse
	(*GetUserProgressRequest)(nil),         // 11: progress.GetUserProgressRequest
	(*GetUserProgressResponse)(nil),        // 12: progress.GetUserProgressResponse
	(*GetCourseProgressRequest)(nil),       // 13: progress.GetCourseProgressRequest
	(*GetCourseProgressResponse)(nil),      // 14: progress.GetCourseProgressResponse
	(*CreateEnrollmentRequest)(nil),        // 15: progress.CreateEnrollmentRequest
	(*CreateEnrollmentResponse)(nil),       // 16: progress.CreateEnrollmentResponse
	(*GetEnrollmentRequest)(nil),           // 17: progress.GetEnrollmentRequest
	(*GetEnrollmentResponse)(nil),          // 18: progress.GetEnrollmentResponse
	(*ListEnrollmentsRequest)(nil),         // 19: progress.ListEnrollmentsRequest
	(*ListEnrollmentsResponse)(nil),        // 20: progress.ListEnrollmentsResponse
	(*UpdateEnrollmentStatusRequest)(nil),  // 21: progress.UpdateEnrollmentStatusRequest
	(*UpdateEnrollmentStatusResponse)(nil), // 22: progress.UpdateEnrollmentStatusResponse
	(*MarkLectureCompleteRequest)(nil),     // 23: progress.MarkLectureCompleteRequest
	(*MarkLectureCompleteResponse)(nil),    // 24: progress.MarkLectureCompleteResponse
	(*GetLectureProgressRequest)(nil),      // 25: progress.GetLectureProgressRequest
	(*GetLectureProgressResponse)(nil),     // 26: progress.GetLectureProgressResponse
	(*GetCourseCompletionRequest)(nil),     // 27: progress.GetCourseCompletionRequest
	(*GetCourseCompletionResponse)(nil),    // 28: progress.GetCourseCompletionResponse
	(*GetUserAnalyticsRequest)(nil),        // 29: progress.GetUserAnalyticsRequest
	(*GetUserAnalyticsResponse)(nil),       // 30: progress.GetUserAnalyticsResponse
	(*GetCourseAnalyticsRequest)(nil),      // 31: progress.GetCourseAnalyticsRequest
	(*GetCourseAnalyticsResponse)(nil),     // 32: progress.GetCourseAnalyticsResponse
	(*GetInstructorAnalyticsRequest)(nil),  // 33: progress.GetInstructorAnalyticsRequest
	(*GetInstructorAnalyticsResponse)(nil), // 34: progress.GetInstructorAnalyticsResponse
	(*timestamppb.Timestamp)(nil),          // 35: google.protobuf.Timestamp
}
var file_proto_progress_proto_depIdxs = []int32{
	35, // 0: progress.UserProgress.last_accessed:type_name -> google.protobuf.Timestamp
	35, // 1: progress.UserProgress.completed_at:type_name -> google.protobuf.Timestamp
	35, // 2: progress.UserProgress.created_at:type_name -> google.protobuf.Timestamp
	35, // 3: progress.UserProgress.updated_at:type_name -> google.protobuf.Timestamp
	35, // 4: progress.Enrollment.enrolled_at:type_name -> google.protobuf.Timestamp
	35, // 5: progress.Enrollment.completed_at:type_name -> google.protobuf.Timestamp
	35, // 6: progress.Enrollment.last_accessed:type_name -> google.protobuf.Timestamp
	35, // 7: progress.Enrollment.created_at:type_name -> google.protobuf.Timestamp
	35, // 8: progress.Enrollment.updated_at:type_name -> google.protobuf.Timestamp
	35, // 9: progress.LectureProgress.last_accessed:type_name -> google.protobuf.Timestamp
	35, // 10: progress.LectureProgress.completed_at:type_name -> google.protobuf.Timestamp
	2,  // 11: progress.CourseCompletion.lecture_progress:type_name -> progress.LectureProgress
	35, // 12: progress.CourseCompletion.started_at:type_name -> google.protobuf.Timestamp
	35, // 13: progress.CourseCompletion.completed_at:type_name -> google.protobuf.Timestamp
	35, // 14: progress.CourseCompletion.last_accessed:type_name -> google.protobuf.Timestamp
	35, // 15: progress.UserAnalytics.last_activity:type_name -> google.protobuf.Timestamp
	0,  // 16: progress.UpdateProgressResponse.progress:type_name -> progress.UserProgress
	0,  // 17: progress.GetProgressResponse.progress:type_name -> progress.UserProgress
	0,  // 18: progress.GetUserProgressResponse.progress:type_name -> progress.UserProgress
	0,  // 19: progress.GetCourseProgressResponse.progress:type_name -> progress.UserProgress
	1,  // 20: progress.CreateEnrollmentResponse.enrollment:type_name -> progress.Enrollment
	1,  // 21: progress.GetEnrollmentResponse.enrollment:type_name -> progress.Enrollment
	1,  // 22: progress.ListEnrollmentsResponse.enrollments:type_name -> progress.Enrollment
	1,  // 23: progress.UpdateEnrollmentStatusResponse.enrollment:type_name -> progress.Enrollment
	0,  // 24: progress.MarkLectureCompleteResponse.progress:type_name -> progress.UserProgress
	2,  // 25: progress.GetLectureProgressResponse.lecture_progress:type_name -> progress.LectureProgress
	3,  // 26: progress.GetCourseCompletionResponse.completion:type_name -> progress.CourseCompletion
	4,  // 27: progress.GetUserAnalyticsResponse.analytics:type_name -> progress.UserAnalytics
	5,  // 28: progress.GetCourseAnalyticsResponse.analytics:type_name -> progress.CourseAnalytics
	6,  // 29: progress.GetInstructorAnalyticsResponse.analytics:type_name -> progress.InstructorAnalytics
	7,  // 30: progress.ProgressService.UpdateProgress:input_type -> progress.UpdateProgressRequest
	9,  // 31: progress.ProgressService.GetProgress:input_type -> progress.GetProgressRequest
	11, // 32: progress.ProgressService.GetUserProgress:input_type -> progress.GetUserProgressRequest
	13, // 33: progress.ProgressService.GetCourseProgress:input_type -> progress.GetCourseProgressRequest
	15, // 34: progress.ProgressService.CreateEnrollment:input_type -> progress.CreateEnrollmentRequest
	17, // 35: progress.ProgressService.GetEnrollment:input_type -> progress.GetEnrollmentRequest
	19, // 36: progress.ProgressService.ListEnrollments:input_type -> progress.ListEnrollmentsRequest
	21, // 37: progress.ProgressService.UpdateEnrollmentStatus:input_type -> progress.UpdateEnrollmentStatusRequest
	23, // 38: progress.ProgressService.MarkLectureComplete:input_type -> progress.MarkLectureCompleteRequest
	25, // 39: progress.ProgressService.GetLectureProgress:input_type -> progress.GetLectureProgressRequest
	27, // 40: progress.ProgressService.GetCourseCompletion:input_type -> progress.GetCourseCompletionRequest
	29, // 41: progress.ProgressService.GetUserAnalytics:input_type -> progress.GetUserAnalyticsRequest
	31, // 42: progress.ProgressService.GetCourseAnalytics:input_type -> progress.GetCourseAnalyticsRequest
	33, // 43: progress.ProgressService.GetInstructorAnalytics:input_type -> progress.GetInstructorAnalyticsRequest
	8,  // 44: progress.ProgressService.UpdateProgress:output_type -> progress.UpdateProgressResponse
	10, // 45: progress.ProgressService.GetProgress:output_type -> progress.GetProgressResponse
	12, // 46: progress.ProgressService.GetUserProgress:output_type -> progress.GetUserProgressResponse
	14, // 47: progress.ProgressService.GetCourseProgress:output_type -> progress.GetCourseProgressResponse
	16, // 48: progress.ProgressService.CreateEnrollment:output_type -> progress.CreateEnrollmentResponse
	18, // 49: progress.ProgressService.GetEnrollment:output_type -> progress.GetEnrollmentResponse
	20, // 50: progress.ProgressService.ListEnrollments:output_type -> progress.ListEnrollmentsResponse
	22, // 51: progress.ProgressService.UpdateEnrollmentStatus:output_type -> progress.UpdateEnrollmentStatusResponse
	24, // 52: progress.ProgressService.MarkLectureComplete:output_type -> progress.MarkLectureCompleteResponse
	26, // 53: progress.ProgressService.GetLectureProgress:output_type -> progress.GetLectureProgressResponse
	28, // 54: progress.ProgressService.GetCourseCompletion:output_type -> progress.GetCourseCompletionResponse
	30, // 55: progress.ProgressService.GetUserAnalytics:output_type -> progress.GetUserAnalyticsResponse
	32, // 56: progress.ProgressService.GetCourseAnalytics:output_type -> progress.GetCourseAnalyticsResponse
	34, // 57: progress.ProgressService.GetInstructorAnalytics:output_type -> progress.GetInstructorAnalyticsResponse
	44, // [44:58] is the sub-list for method output_type
	30, // [30:44] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_proto_progress_proto_init() }
func file_proto_progress_proto_init() {
	if File_proto_progress_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_progress_proto_rawDesc), len(file_proto_progress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_progress_proto_goTypes,
		DependencyIndexes: file_proto_progress_proto_depIdxs,
		MessageInfos:      file_proto_progress_proto_msgTypes,
	}.Build()
	File_proto_progress_proto = out.File
	file_proto_progress_proto_goTypes = nil
	file_proto_progress_proto_depIdxs = nil
}
