// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/course.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CourseService_CreateCourse_FullMethodName    = "/course.CourseService/CreateCourse"
	CourseService_GetCourse_FullMethodName       = "/course.CourseService/GetCourse"
	CourseService_UpdateCourse_FullMethodName    = "/course.CourseService/UpdateCourse"
	CourseService_DeleteCourse_FullMethodName    = "/course.CourseService/DeleteCourse"
	CourseService_ListCourses_FullMethodName     = "/course.CourseService/ListCourses"
	CourseService_SearchCourses_FullMethodName   = "/course.CourseService/SearchCourses"
	CourseService_CreateLecture_FullMethodName   = "/course.CourseService/CreateLecture"
	CourseService_GetLecture_FullMethodName      = "/course.CourseService/GetLecture"
	CourseService_UpdateLecture_FullMethodName   = "/course.CourseService/UpdateLecture"
	CourseService_DeleteLecture_FullMethodName   = "/course.CourseService/DeleteLecture"
	CourseService_ListLectures_FullMethodName    = "/course.CourseService/ListLectures"
	CourseService_EnrollInCourse_FullMethodName  = "/course.CourseService/EnrollInCourse"
	CourseService_GetEnrollment_FullMethodName   = "/course.CourseService/GetEnrollment"
	CourseService_ListEnrollments_FullMethodName = "/course.CourseService/ListEnrollments"
)

// CourseServiceClient is the client API for CourseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CourseServiceClient interface {
	// Course management
	CreateCourse(ctx context.Context, in *CreateCourseRequest, opts ...grpc.CallOption) (*CreateCourseResponse, error)
	GetCourse(ctx context.Context, in *GetCourseRequest, opts ...grpc.CallOption) (*GetCourseResponse, error)
	UpdateCourse(ctx context.Context, in *UpdateCourseRequest, opts ...grpc.CallOption) (*UpdateCourseResponse, error)
	DeleteCourse(ctx context.Context, in *DeleteCourseRequest, opts ...grpc.CallOption) (*DeleteCourseResponse, error)
	ListCourses(ctx context.Context, in *ListCoursesRequest, opts ...grpc.CallOption) (*ListCoursesResponse, error)
	SearchCourses(ctx context.Context, in *SearchCoursesRequest, opts ...grpc.CallOption) (*SearchCoursesResponse, error)
	// Lecture management
	CreateLecture(ctx context.Context, in *CreateLectureRequest, opts ...grpc.CallOption) (*CreateLectureResponse, error)
	GetLecture(ctx context.Context, in *GetLectureRequest, opts ...grpc.CallOption) (*GetLectureResponse, error)
	UpdateLecture(ctx context.Context, in *UpdateLectureRequest, opts ...grpc.CallOption) (*UpdateLectureResponse, error)
	DeleteLecture(ctx context.Context, in *DeleteLectureRequest, opts ...grpc.CallOption) (*DeleteLectureResponse, error)
	ListLectures(ctx context.Context, in *ListLecturesRequest, opts ...grpc.CallOption) (*ListLecturesResponse, error)
	// Course enrollment
	EnrollInCourse(ctx context.Context, in *EnrollInCourseRequest, opts ...grpc.CallOption) (*EnrollInCourseResponse, error)
	GetEnrollment(ctx context.Context, in *GetEnrollmentRequest, opts ...grpc.CallOption) (*GetEnrollmentResponse, error)
	ListEnrollments(ctx context.Context, in *ListEnrollmentsRequest, opts ...grpc.CallOption) (*ListEnrollmentsResponse, error)
}

type courseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCourseServiceClient(cc grpc.ClientConnInterface) CourseServiceClient {
	return &courseServiceClient{cc}
}

func (c *courseServiceClient) CreateCourse(ctx context.Context, in *CreateCourseRequest, opts ...grpc.CallOption) (*CreateCourseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCourseResponse)
	err := c.cc.Invoke(ctx, CourseService_CreateCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) GetCourse(ctx context.Context, in *GetCourseRequest, opts ...grpc.CallOption) (*GetCourseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCourseResponse)
	err := c.cc.Invoke(ctx, CourseService_GetCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) UpdateCourse(ctx context.Context, in *UpdateCourseRequest, opts ...grpc.CallOption) (*UpdateCourseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCourseResponse)
	err := c.cc.Invoke(ctx, CourseService_UpdateCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) DeleteCourse(ctx context.Context, in *DeleteCourseRequest, opts ...grpc.CallOption) (*DeleteCourseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCourseResponse)
	err := c.cc.Invoke(ctx, CourseService_DeleteCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) ListCourses(ctx context.Context, in *ListCoursesRequest, opts ...grpc.CallOption) (*ListCoursesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCoursesResponse)
	err := c.cc.Invoke(ctx, CourseService_ListCourses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) SearchCourses(ctx context.Context, in *SearchCoursesRequest, opts ...grpc.CallOption) (*SearchCoursesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchCoursesResponse)
	err := c.cc.Invoke(ctx, CourseService_SearchCourses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) CreateLecture(ctx context.Context, in *CreateLectureRequest, opts ...grpc.CallOption) (*CreateLectureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLectureResponse)
	err := c.cc.Invoke(ctx, CourseService_CreateLecture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) GetLecture(ctx context.Context, in *GetLectureRequest, opts ...grpc.CallOption) (*GetLectureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLectureResponse)
	err := c.cc.Invoke(ctx, CourseService_GetLecture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) UpdateLecture(ctx context.Context, in *UpdateLectureRequest, opts ...grpc.CallOption) (*UpdateLectureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLectureResponse)
	err := c.cc.Invoke(ctx, CourseService_UpdateLecture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) DeleteLecture(ctx context.Context, in *DeleteLectureRequest, opts ...grpc.CallOption) (*DeleteLectureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLectureResponse)
	err := c.cc.Invoke(ctx, CourseService_DeleteLecture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) ListLectures(ctx context.Context, in *ListLecturesRequest, opts ...grpc.CallOption) (*ListLecturesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLecturesResponse)
	err := c.cc.Invoke(ctx, CourseService_ListLectures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) EnrollInCourse(ctx context.Context, in *EnrollInCourseRequest, opts ...grpc.CallOption) (*EnrollInCourseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollInCourseResponse)
	err := c.cc.Invoke(ctx, CourseService_EnrollInCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) GetEnrollment(ctx context.Context, in *GetEnrollmentRequest, opts ...grpc.CallOption) (*GetEnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEnrollmentResponse)
	err := c.cc.Invoke(ctx, CourseService_GetEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) ListEnrollments(ctx context.Context, in *ListEnrollmentsRequest, opts ...grpc.CallOption) (*ListEnrollmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnrollmentsResponse)
	err := c.cc.Invoke(ctx, CourseService_ListEnrollments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CourseServiceServer is the server API for CourseService service.
// All implementations must embed UnimplementedCourseServiceServer
// for forward compatibility.
type CourseServiceServer interface {
	// Course management
	CreateCourse(context.Context, *CreateCourseRequest) (*CreateCourseResponse, error)
	GetCourse(context.Context, *GetCourseRequest) (*GetCourseResponse, error)
	UpdateCourse(context.Context, *UpdateCourseRequest) (*UpdateCourseResponse, error)
	DeleteCourse(context.Context, *DeleteCourseRequest) (*DeleteCourseResponse, error)
	ListCourses(context.Context, *ListCoursesRequest) (*ListCoursesResponse, error)
	SearchCourses(context.Context, *SearchCoursesRequest) (*SearchCoursesResponse, error)
	// Lecture management
	CreateLecture(context.Context, *CreateLectureRequest) (*CreateLectureResponse, error)
	GetLecture(context.Context, *GetLectureRequest) (*GetLectureResponse, error)
	UpdateLecture(context.Context, *UpdateLectureRequest) (*UpdateLectureResponse, error)
	DeleteLecture(context.Context, *DeleteLectureRequest) (*DeleteLectureResponse, error)
	ListLectures(context.Context, *ListLecturesRequest) (*ListLecturesResponse, error)
	// Course enrollment
	EnrollInCourse(context.Context, *EnrollInCourseRequest) (*EnrollInCourseResponse, error)
	GetEnrollment(context.Context, *GetEnrollmentRequest) (*GetEnrollmentResponse, error)
	ListEnrollments(context.Context, *ListEnrollmentsRequest) (*ListEnrollmentsResponse, error)
	mustEmbedUnimplementedCourseServiceServer()
}

// UnimplementedCourseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCourseServiceServer struct{}

func (UnimplementedCourseServiceServer) CreateCourse(context.Context, *CreateCourseRequest) (*CreateCourseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCourse not implemented")
}
func (UnimplementedCourseServiceServer) GetCourse(context.Context, *GetCourseRequest) (*GetCourseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourse not implemented")
}
func (UnimplementedCourseServiceServer) UpdateCourse(context.Context, *UpdateCourseRequest) (*UpdateCourseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCourse not implemented")
}
func (UnimplementedCourseServiceServer) DeleteCourse(context.Context, *DeleteCourseRequest) (*DeleteCourseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCourse not implemented")
}
func (UnimplementedCourseServiceServer) ListCourses(context.Context, *ListCoursesRequest) (*ListCoursesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCourses not implemented")
}
func (UnimplementedCourseServiceServer) SearchCourses(context.Context, *SearchCoursesRequest) (*SearchCoursesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchCourses not implemented")
}
func (UnimplementedCourseServiceServer) CreateLecture(context.Context, *CreateLectureRequest) (*CreateLectureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLecture not implemented")
}
func (UnimplementedCourseServiceServer) GetLecture(context.Context, *GetLectureRequest) (*GetLectureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLecture not implemented")
}
func (UnimplementedCourseServiceServer) UpdateLecture(context.Context, *UpdateLectureRequest) (*UpdateLectureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLecture not implemented")
}
func (UnimplementedCourseServiceServer) DeleteLecture(context.Context, *DeleteLectureRequest) (*DeleteLectureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLecture not implemented")
}
func (UnimplementedCourseServiceServer) ListLectures(context.Context, *ListLecturesRequest) (*ListLecturesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLectures not implemented")
}
func (UnimplementedCourseServiceServer) EnrollInCourse(context.Context, *EnrollInCourseRequest) (*EnrollInCourseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnrollInCourse not implemented")
}
func (UnimplementedCourseServiceServer) GetEnrollment(context.Context, *GetEnrollmentRequest) (*GetEnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnrollment not implemented")
}
func (UnimplementedCourseServiceServer) ListEnrollments(context.Context, *ListEnrollmentsRequest) (*ListEnrollmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEnrollments not implemented")
}
func (UnimplementedCourseServiceServer) mustEmbedUnimplementedCourseServiceServer() {}
func (UnimplementedCourseServiceServer) testEmbeddedByValue()                       {}

// UnsafeCourseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CourseServiceServer will
// result in compilation errors.
type UnsafeCourseServiceServer interface {
	mustEmbedUnimplementedCourseServiceServer()
}

func RegisterCourseServiceServer(s grpc.ServiceRegistrar, srv CourseServiceServer) {
	// If the following call pancis, it indicates UnimplementedCourseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CourseService_ServiceDesc, srv)
}

func _CourseService_CreateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).CreateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_CreateCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).CreateCourse(ctx, req.(*CreateCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_GetCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).GetCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_GetCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).GetCourse(ctx, req.(*GetCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_UpdateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).UpdateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_UpdateCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).UpdateCourse(ctx, req.(*UpdateCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_DeleteCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).DeleteCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_DeleteCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).DeleteCourse(ctx, req.(*DeleteCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_ListCourses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCoursesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).ListCourses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_ListCourses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).ListCourses(ctx, req.(*ListCoursesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_SearchCourses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCoursesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).SearchCourses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_SearchCourses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).SearchCourses(ctx, req.(*SearchCoursesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_CreateLecture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLectureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).CreateLecture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_CreateLecture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).CreateLecture(ctx, req.(*CreateLectureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_GetLecture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLectureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).GetLecture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_GetLecture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).GetLecture(ctx, req.(*GetLectureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_UpdateLecture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLectureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).UpdateLecture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_UpdateLecture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).UpdateLecture(ctx, req.(*UpdateLectureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_DeleteLecture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLectureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).DeleteLecture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_DeleteLecture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).DeleteLecture(ctx, req.(*DeleteLectureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_ListLectures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLecturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).ListLectures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_ListLectures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).ListLectures(ctx, req.(*ListLecturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_EnrollInCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollInCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).EnrollInCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_EnrollInCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).EnrollInCourse(ctx, req.(*EnrollInCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_GetEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).GetEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_GetEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).GetEnrollment(ctx, req.(*GetEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_ListEnrollments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnrollmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).ListEnrollments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseService_ListEnrollments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).ListEnrollments(ctx, req.(*ListEnrollmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CourseService_ServiceDesc is the grpc.ServiceDesc for CourseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CourseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "course.CourseService",
	HandlerType: (*CourseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCourse",
			Handler:    _CourseService_CreateCourse_Handler,
		},
		{
			MethodName: "GetCourse",
			Handler:    _CourseService_GetCourse_Handler,
		},
		{
			MethodName: "UpdateCourse",
			Handler:    _CourseService_UpdateCourse_Handler,
		},
		{
			MethodName: "DeleteCourse",
			Handler:    _CourseService_DeleteCourse_Handler,
		},
		{
			MethodName: "ListCourses",
			Handler:    _CourseService_ListCourses_Handler,
		},
		{
			MethodName: "SearchCourses",
			Handler:    _CourseService_SearchCourses_Handler,
		},
		{
			MethodName: "CreateLecture",
			Handler:    _CourseService_CreateLecture_Handler,
		},
		{
			MethodName: "GetLecture",
			Handler:    _CourseService_GetLecture_Handler,
		},
		{
			MethodName: "UpdateLecture",
			Handler:    _CourseService_UpdateLecture_Handler,
		},
		{
			MethodName: "DeleteLecture",
			Handler:    _CourseService_DeleteLecture_Handler,
		},
		{
			MethodName: "ListLectures",
			Handler:    _CourseService_ListLectures_Handler,
		},
		{
			MethodName: "EnrollInCourse",
			Handler:    _CourseService_EnrollInCourse_Handler,
		},
		{
			MethodName: "GetEnrollment",
			Handler:    _CourseService_GetEnrollment_Handler,
		},
		{
			MethodName: "ListEnrollments",
			Handler:    _CourseService_ListEnrollments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/course.proto",
}

const (
	AccessValidationService_ValidateCourseAccess_FullMethodName   = "/course.AccessValidationService/ValidateCourseAccess"
	AccessValidationService_ValidateLectureAccess_FullMethodName  = "/course.AccessValidationService/ValidateLectureAccess"
	AccessValidationService_ValidateResourceAccess_FullMethodName = "/course.AccessValidationService/ValidateResourceAccess"
	AccessValidationService_BatchValidateAccess_FullMethodName    = "/course.AccessValidationService/BatchValidateAccess"
)

// AccessValidationServiceClient is the client API for AccessValidationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccessValidationServiceClient interface {
	// Access validation
	ValidateCourseAccess(ctx context.Context, in *ValidateCourseAccessRequest, opts ...grpc.CallOption) (*ValidateCourseAccessResponse, error)
	ValidateLectureAccess(ctx context.Context, in *ValidateLectureAccessRequest, opts ...grpc.CallOption) (*ValidateLectureAccessResponse, error)
	ValidateResourceAccess(ctx context.Context, in *ValidateResourceAccessRequest, opts ...grpc.CallOption) (*ValidateResourceAccessResponse, error)
	BatchValidateAccess(ctx context.Context, in *BatchValidateAccessRequest, opts ...grpc.CallOption) (*BatchValidateAccessResponse, error)
}

type accessValidationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessValidationServiceClient(cc grpc.ClientConnInterface) AccessValidationServiceClient {
	return &accessValidationServiceClient{cc}
}

func (c *accessValidationServiceClient) ValidateCourseAccess(ctx context.Context, in *ValidateCourseAccessRequest, opts ...grpc.CallOption) (*ValidateCourseAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateCourseAccessResponse)
	err := c.cc.Invoke(ctx, AccessValidationService_ValidateCourseAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessValidationServiceClient) ValidateLectureAccess(ctx context.Context, in *ValidateLectureAccessRequest, opts ...grpc.CallOption) (*ValidateLectureAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateLectureAccessResponse)
	err := c.cc.Invoke(ctx, AccessValidationService_ValidateLectureAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessValidationServiceClient) ValidateResourceAccess(ctx context.Context, in *ValidateResourceAccessRequest, opts ...grpc.CallOption) (*ValidateResourceAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResourceAccessResponse)
	err := c.cc.Invoke(ctx, AccessValidationService_ValidateResourceAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessValidationServiceClient) BatchValidateAccess(ctx context.Context, in *BatchValidateAccessRequest, opts ...grpc.CallOption) (*BatchValidateAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchValidateAccessResponse)
	err := c.cc.Invoke(ctx, AccessValidationService_BatchValidateAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessValidationServiceServer is the server API for AccessValidationService service.
// All implementations must embed UnimplementedAccessValidationServiceServer
// for forward compatibility.
type AccessValidationServiceServer interface {
	// Access validation
	ValidateCourseAccess(context.Context, *ValidateCourseAccessRequest) (*ValidateCourseAccessResponse, error)
	ValidateLectureAccess(context.Context, *ValidateLectureAccessRequest) (*ValidateLectureAccessResponse, error)
	ValidateResourceAccess(context.Context, *ValidateResourceAccessRequest) (*ValidateResourceAccessResponse, error)
	BatchValidateAccess(context.Context, *BatchValidateAccessRequest) (*BatchValidateAccessResponse, error)
	mustEmbedUnimplementedAccessValidationServiceServer()
}

// UnimplementedAccessValidationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccessValidationServiceServer struct{}

func (UnimplementedAccessValidationServiceServer) ValidateCourseAccess(context.Context, *ValidateCourseAccessRequest) (*ValidateCourseAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateCourseAccess not implemented")
}
func (UnimplementedAccessValidationServiceServer) ValidateLectureAccess(context.Context, *ValidateLectureAccessRequest) (*ValidateLectureAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateLectureAccess not implemented")
}
func (UnimplementedAccessValidationServiceServer) ValidateResourceAccess(context.Context, *ValidateResourceAccessRequest) (*ValidateResourceAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateResourceAccess not implemented")
}
func (UnimplementedAccessValidationServiceServer) BatchValidateAccess(context.Context, *BatchValidateAccessRequest) (*BatchValidateAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchValidateAccess not implemented")
}
func (UnimplementedAccessValidationServiceServer) mustEmbedUnimplementedAccessValidationServiceServer() {
}
func (UnimplementedAccessValidationServiceServer) testEmbeddedByValue() {}

// UnsafeAccessValidationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessValidationServiceServer will
// result in compilation errors.
type UnsafeAccessValidationServiceServer interface {
	mustEmbedUnimplementedAccessValidationServiceServer()
}

func RegisterAccessValidationServiceServer(s grpc.ServiceRegistrar, srv AccessValidationServiceServer) {
	// If the following call pancis, it indicates UnimplementedAccessValidationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccessValidationService_ServiceDesc, srv)
}

func _AccessValidationService_ValidateCourseAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCourseAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessValidationServiceServer).ValidateCourseAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessValidationService_ValidateCourseAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessValidationServiceServer).ValidateCourseAccess(ctx, req.(*ValidateCourseAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessValidationService_ValidateLectureAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateLectureAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessValidationServiceServer).ValidateLectureAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessValidationService_ValidateLectureAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessValidationServiceServer).ValidateLectureAccess(ctx, req.(*ValidateLectureAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessValidationService_ValidateResourceAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateResourceAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessValidationServiceServer).ValidateResourceAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessValidationService_ValidateResourceAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessValidationServiceServer).ValidateResourceAccess(ctx, req.(*ValidateResourceAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessValidationService_BatchValidateAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchValidateAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessValidationServiceServer).BatchValidateAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessValidationService_BatchValidateAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessValidationServiceServer).BatchValidateAccess(ctx, req.(*BatchValidateAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessValidationService_ServiceDesc is the grpc.ServiceDesc for AccessValidationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessValidationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "course.AccessValidationService",
	HandlerType: (*AccessValidationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateCourseAccess",
			Handler:    _AccessValidationService_ValidateCourseAccess_Handler,
		},
		{
			MethodName: "ValidateLectureAccess",
			Handler:    _AccessValidationService_ValidateLectureAccess_Handler,
		},
		{
			MethodName: "ValidateResourceAccess",
			Handler:    _AccessValidationService_ValidateResourceAccess_Handler,
		},
		{
			MethodName: "BatchValidateAccess",
			Handler:    _AccessValidationService_BatchValidateAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/course.proto",
}
